In [37]:
import pandas as pd

df = pd.read_csv("./GSAF5.csv", encoding="latin1")
display(df.head())

print(df.columns)
print(df.shape)

null_cols = df.isnull().sum()
print(null_cols)

display(df[df["Unnamed: 22"].isnull() == False])
display(df[df["Unnamed: 23"].isnull() == False])

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,...,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23
0,2016.09.18.c,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,male,M,...,NaN,"Orlando Sentinel, 9/19/2016",2016.09.18.c-NSB.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.18.c,2016.09.18.c,5993,NaN,NaN
1,2016.09.18.b,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,Chucky Luciano,M,...,NaN,"Orlando Sentinel, 9/19/2016",2016.09.18.b-Luciano.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.18.b,2016.09.18.b,5992,NaN,NaN
2,2016.09.18.a,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,male,M,...,NaN,"Orlando Sentinel, 9/19/2016",2016.09.18.a-NSB.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.18.a,2016.09.18.a,5991,NaN,NaN
3,2016.09.17,17-Sep-16,2016,Unprovoked,AUSTRALIA,Victoria,Thirteenth Beach,Surfing,Rory Angiolella,M,...,NaN,"The Age, 9/18/2016",2016.09.17-Angiolella.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.17,2016.09.17,5990,NaN,NaN
4,2016.09.15,16-Sep-16,2016,Unprovoked,AUSTRALIA,Victoria,Bells Beach,Surfing,male,M,...,2 m shark,"The Age, 9/16/2016",2016.09.16-BellsBeach.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.16,2016.09.15,5989,NaN,NaN

Index(['Case Number', 'Date', 'Year', 'Type', 'Country', 'Area', 'Location',
       'Activity', 'Name', 'Sex ', 'Age', 'Injury', 'Fatal (Y/N)', 'Time',
       'Species ', 'Investigator or Source', 'pdf', 'href formula', 'href',
       'Case Number.1', 'Case Number.2', 'original order', 'Unnamed: 22',
       'Unnamed: 23'],
      dtype='object')
(5992, 24)
Case Number                  0
Date                         0
Year                         0
Type                         0
Country                     43
Area                       402
Location                   496
Activity                   527
Name                       200
Sex                        567
Age                       2681
Injury                      27
Fatal (Y/N)                 19
Time                      3213
Species                   2934
Investigator or Source      15
pdf                          0
href formula                 1
href                         3
Case Number.1                0
Case Number.2                0
original order               0
Unnamed: 22               5991
Unnamed: 23               5990
dtype: int64

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,...,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23
1247,2006.06.18,18-Jun-06,2006,Unprovoked,BRAZIL,Pernambuco,"Punta Del Chifre Beach, Olinda",Body boarding,Humberto Pessoa Batista,M,...,NaN,globalsurfnews.com,2006.06.18-Batista.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2006.06.18,2006.06.18,4746,stopped here,NaN

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,...,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23
4182,1952.07.13,13-Jul-52,1952,Provoked,USA,California,"San Diego, San Diego County",Fishing,"Gerald Howard, on board sportsfishing boat Ter...",M,...,NaN,"L.A. Times, 7/14/1952",1952.07.13-Howard.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1952.07.13,1952.07.13,1811,NaN,Teramo
5585,1879.03.10,10-Mar-1879,1879,Invalid,AUSTRALIA,New South Wales,Near Sydney,The steamship Bonnie Dundee lost in collision,Cabin boy of the Bonnie Dundee,M,...,NaN,"Star, 3/22/1879",1879.03.10-Bonnie-Dundee.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1879.03.10,1879.03.10,408,NaN,change filename

He comprobado que las columnas sin nombre están vacías y las 3 que tienen información, no son relevantes.

In [41]:
drop_cols = list(null_cols[null_cols > 5900].index)
df_cleaning = df.drop(drop_cols, axis = 1).copy()
# df_cleaning = df_cleaning.drop(["pdf", "href formula", "href"], axis = 1).copy()

df_cleaning.head()

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,...,Fatal (Y/N),Time,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order
0,2016.09.18.c,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,male,M,...,N,13h00,NaN,"Orlando Sentinel, 9/19/2016",2016.09.18.c-NSB.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.18.c,2016.09.18.c,5993
1,2016.09.18.b,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,Chucky Luciano,M,...,N,11h00,NaN,"Orlando Sentinel, 9/19/2016",2016.09.18.b-Luciano.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.18.b,2016.09.18.b,5992
2,2016.09.18.a,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,male,M,...,N,10h43,NaN,"Orlando Sentinel, 9/19/2016",2016.09.18.a-NSB.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.18.a,2016.09.18.a,5991
3,2016.09.17,17-Sep-16,2016,Unprovoked,AUSTRALIA,Victoria,Thirteenth Beach,Surfing,Rory Angiolella,M,...,N,NaN,NaN,"The Age, 9/18/2016",2016.09.17-Angiolella.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.17,2016.09.17,5990
4,2016.09.15,16-Sep-16,2016,Unprovoked,AUSTRALIA,Victoria,Bells Beach,Surfing,male,M,...,N,NaN,2 m shark,"The Age, 9/16/2016",2016.09.16-BellsBeach.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.16,2016.09.15,5989

Por otra parte, las columnas con los enlaces a los pdf, aunque algunos refieren a errores 404, pueden ser valiosos. Contienen información que en ocasiones no ha sido introducida en la dataset. Para no repasar los 6000 datos, voy a
repasar si la información que contienen es útil en los casos que los nulos sean menor que 50, para completar dicha información.

In [47]:
null_cols = df.isnull().sum()
null_cols[(null_cols < 50) & (null_cols > 0)]

Country                   43
Injury                    27
Fatal (Y/N)               19
Investigator or Source    15
href formula               1
href                       3
dtype: int64

In [53]:
null_cols_2 = df[["Country", "Injury", "Fatal (Y/N)", "Investigator or Source"]].isnull().copy()
display(null_cols_2)

      Country  Injury  Fatal (Y/N)  Investigator or Source
0       False   False        False                   False
1       False   False        False                   False
2       False   False        False                   False
3       False   False        False                   False
4       False   False        False                   False
5       False   False        False                   False
6       False   False        False                   False
7       False   False        False                   False
8       False   False        False                   False
9       False   False        False                   False
10      False   False        False                   False
11      False   False        False                   False
12      False   False        False                   False
13      False   False        False                   False
14      False   False        False                   False
15      False   False        False                   False
16      False   False        False                   False
17      False   False        False                   False
18      False   False        False                   False
19      False   False        False                   False
20      False   False        False                   False
21      False   False        False                   False
22      False   False        False                   False
23      False   False        False                   False
24      False   False        False                   False
25      False   False        False                   False
26      False   False        False                   False
27      False   False        False                   False
28      False   False        False                   False
29      False   False        False                   False
...       ...     ...          ...                     ...
5962    False   False        False                   False
5963    False   False        False                   False
5964    False   False        False                   False
5965    False   False        False                   False
5966    False   False        False                   False
5967    False    True        False                   False
5968    False   False        False                   False
5969    False   False        False                   False
5970    False   False        False                   False
5971    False   False        False                   False
5972    False   False        False                   False
5973    False   False        False                   False
5974    False   False        False                   False
5975    False   False        False                   False
5976    False   False        False                   False
5977    False   False        False                   False
5978    False   False        False                   False
5979    False   False        False                   False
5980    False   False        False                   False
5981    False   False        False                   False
5982    False   False        False                   False
5983    False   False        False                   False
5984    False   False        False                   False
5985    False   False        False                   False
5986    False   False        False                   False
5987    False   False        False                   False
5988    False   False        False                   False
5989    False   False        False                   False
5990    False   False        False                   False
5991    False   False        False                   False

[5992 rows x 4 columns]

In [34]:
df_cleaning["Time"].value_counts()

Afternoon                         174
11h00                             123
12h00                             107
Morning                           107
15h00                             100
16h00                              94
14h00                              93
16h30                              72
13h00                              71
14h30                              70
17h30                              69
17h00                              64
15h30                              62
18h00                              62
11h30                              60
Night                              58
13h30                              56
10h00                              53
09h00                              46
10h30                              45
Evening                            33
12h30                              33
Late afternoon                     32
07h30                              30
09h30                              30
08h00                              28
18h30                              27
08h30                              25
19h00                              23
07h00                              20
                                 ...
10h45-11h15                         1
12h46                               1
18h15 to 21h30                      1
19h55                               1
"After lunch"                       1
Before 07h00                        1
12h02                               1
11h30                               1
Between 05h00 and 08h00             1
>14h30                              1
Daybreak                            1
15h53                               1
15h52                               1
10h22                               1
Between 11h00 & 12h00               1
14h30 / 15h30                       1
13h35                               1
Mid morning                         1
18h25                               1
09h00 -10h00                        1
07h56                               1
Late night                          1
23h30                               1
10h43                               1
Sometime between 06h00 & 08hoo      1
"Evening"                           1
08h55                               1
Between 06h00 & 07h20               1
11h51                               1
05h50                               1
Name: Time, Length: 357, dtype: int64

In [35]:
display(df_cleaning["href formula"])

0       http://sharkattackfile.net/spreadsheets/pdf_di...
1       http://sharkattackfile.net/spreadsheets/pdf_di...
2       http://sharkattackfile.net/spreadsheets/pdf_di...
3       http://sharkattackfile.net/spreadsheets/pdf_di...
4       http://sharkattackfile.net/spreadsheets/pdf_di...
5       http://sharkattackfile.net/spreadsheets/pdf_di...
6       http://sharkattackfile.net/spreadsheets/pdf_di...
7       http://sharkattackfile.net/spreadsheets/pdf_di...
8       http://sharkattackfile.net/spreadsheets/pdf_di...
9       http://sharkattackfile.net/spreadsheets/pdf_di...
10      http://sharkattackfile.net/spreadsheets/pdf_di...
11      http://sharkattackfile.net/spreadsheets/pdf_di...
12      http://sharkattackfile.net/spreadsheets/pdf_di...
13      http://sharkattackfile.net/spreadsheets/pdf_di...
14      http://sharkattackfile.net/spreadsheets/pdf_di...
15      http://sharkattackfile.net/spreadsheets/pdf_di...
16      http://sharkattackfile.net/spreadsheets/pdf_di...
17      http://sharkattackfile.net/spreadsheets/pdf_di...
18      http://sharkattackfile.net/spreadsheets/pdf_di...
19      http://sharkattackfile.net/spreadsheets/pdf_di...
20      http://sharkattackfile.net/spreadsheets/pdf_di...
21      http://sharkattackfile.net/spreadsheets/pdf_di...
22      http://sharkattackfile.net/spreadsheets/pdf_di...
23      http://sharkattackfile.net/spreadsheets/pdf_di...
24      http://sharkattackfile.net/spreadsheets/pdf_di...
25      http://sharkattackfile.net/spreadsheets/pdf_di...
26      http://sharkattackfile.net/spreadsheets/pdf_di...
27      http://sharkattackfile.net/spreadsheets/pdf_di...
28      http://sharkattackfile.net/spreadsheets/pdf_di...
29      http://sharkattackfile.net/spreadsheets/pdf_di...
                              ...
5962    http://sharkattackfile.net/spreadsheets/pdf_di...
5963    http://sharkattackfile.net/spreadsheets/pdf_di...
5964    http://sharkattackfile.net/spreadsheets/pdf_di...
5965    http://sharkattackfile.net/spreadsheets/pdf_di...
5966    http://sharkattackfile.net/spreadsheets/pdf_di...
5967    http://sharkattackfile.net/spreadsheets/pdf_di...
5968    http://sharkattackfile.net/spreadsheets/pdf_di...
5969    http://sharkattackfile.net/spreadsheets/pdf_di...
5970    http://sharkattackfile.net/spreadsheets/pdf_di...
5971    http://sharkattackfile.net/spreadsheets/pdf_di...
5972    http://sharkattackfile.net/spreadsheets/pdf_di...
5973    http://sharkattackfile.net/spreadsheets/pdf_di...
5974    http://sharkattackfile.net/spreadsheets/pdf_di...
5975    http://sharkattackfile.net/spreadsheets/pdf_di...
5976    http://sharkattackfile.net/spreadsheets/pdf_di...
5977    http://sharkattackfile.net/spreadsheets/pdf_di...
5978    http://sharkattackfile.net/spreadsheets/pdf_di...
5979    http://sharkattackfile.net/spreadsheets/pdf_di...
5980    http://sharkattackfile.net/spreadsheets/pdf_di...
5981    http://sharkattackfile.net/spreadsheets/pdf_di...
5982    http://sharkattackfile.net/spreadsheets/pdf_di...
5983    http://sharkattackfile.net/spreadsheets/pdf_di...
5984    http://sharkattackfile.net/spreadsheets/pdf_di...
5985    http://sharkattackfile.net/spreadsheets/pdf_di...
5986    http://sharkattackfile.net/spreadsheets/pdf_di...
5987    http://sharkattackfile.net/spreadsheets/pdf_di...
5988    http://sharkattackfile.net/spreadsheets/pdf_di...
5989    http://sharkattackfile.net/spreadsheets/pdf_di...
5990    http://sharkattackfile.net/spreadsheets/pdf_di...
5991    http://sharkattackfile.net/spreadsheets/pdf_di...
Name: href formula, Length: 5992, dtype: object

In [38]:
df_cleaning["Year"].value_counts()

2015    139
2011    128
2014    125
0       124
2013    122
2008    121
2009    120
2012    117
2007    112
2006    103
2016    103
2005    103
2010    101
2000     97
1959     93
1960     93
2001     92
2004     92
2003     92
2002     88
1962     86
1961     78
1995     76
1964     66
1998     65
1999     65
1996     61
1963     61
1966     58
1997     57
       ...
1785      1
1834      1
1791      1
1733      1
1721      1
1637      1
1617      1
77        1
5         1
1703      1
1755      1
1767      1
1771      1
1779      1
1787      1
1803      1
1749      1
1807      1
1811      1
1819      1
1805      1
1831      1
1555      1
1738      1
1859      1
1742      1
1758      1
1818      1
1822      1
1595      1
Name: Year, Length: 232, dtype: int64

In [54]:
df_cleaning["Date"].value_counts()

1957                          11
1942                           9
1956                           8
1950                           7
1941                           7
1958                           7
No date                        6
1949                           6
05-Oct-03                      5
1955                           5
28-Jul-95                      5
12-Apr-01                      5
No date, Before 1963           5
1959                           5
1940                           5
Aug-56                         5
1954                           5
1970s                          5
Oct-60                         5
1890                           4
Before 1906                    4
28-Dec-14                      4
27-Dec-08                      4
1960s                          4
Before 1958                    4
1945                           4
1961                           4
09-Jul-94                      4
1876                           4
1898                           4
                              ..
05-Jul-75                      1
Reported 28-Mar-1924           1
11-Oct-16                      1
Summer of 1883                 1
06-Aug-16                      1
12-Jul-83                      1
11-Apr-59                      1
22-Mar-31                      1
No date, Before 8-May-1965     1
01-Sep-16                      1
21-Apr-02                      1
26-Apr-15                      1
Reported 06-Jul-1920           1
23-Apr-16                      1
24-Oct-98                      1
22-Apr-99                      1
02-May-16                      1
21-Mar-72                      1
26-Apr-98                      1
10-Mar-82                      1
15-Jun-25                      1
27-May-28                      1
16-Aug-66                      1
12-Aug-07                      1
27-Mar-09                      1
Dec-86                         1
28-Oct-50                      1
03-Jul-14                      1
Before 1916                    1
19-Jan-05                      1
Name: Date, Length: 5128, dtype: int64

Las columnas Date y Year no tienen nulos. Sin embargo, muchos registros tienen formatos diferentes y datos erróneos.
Como las fechas también están en los `case numbers`, crearemos 3 columnas nuevas: año, mes y día con los datos correctos.

In [77]:
df_clean = pd.DataFrame(columns=[])

df_fechas["Date"] = df_cleaning["Date"].copy()
display(df_fechas.head())

#df_fechas["Year"] = df_fechas["Case Number"]

0    2016.09.18.c
1    2016.09.18.b
2    2016.09.18.a
3      2016.09.17
4      2016.09.15
Name: Case Number, dtype: object

In [78]:
df_cleaning["Date"].value_counts()

1957                          11
1942                           9
1956                           8
1950                           7
1941                           7
1958                           7
No date                        6
1949                           6
05-Oct-03                      5
1955                           5
28-Jul-95                      5
12-Apr-01                      5
No date, Before 1963           5
1959                           5
1940                           5
Aug-56                         5
1954                           5
1970s                          5
Oct-60                         5
1890                           4
Before 1906                    4
28-Dec-14                      4
27-Dec-08                      4
1960s                          4
Before 1958                    4
1945                           4
1961                           4
09-Jul-94                      4
1876                           4
1898                           4
                              ..
05-Jul-75                      1
Reported 28-Mar-1924           1
11-Oct-16                      1
Summer of 1883                 1
06-Aug-16                      1
12-Jul-83                      1
11-Apr-59                      1
22-Mar-31                      1
No date, Before 8-May-1965     1
01-Sep-16                      1
21-Apr-02                      1
26-Apr-15                      1
Reported 06-Jul-1920           1
23-Apr-16                      1
24-Oct-98                      1
22-Apr-99                      1
02-May-16                      1
21-Mar-72                      1
26-Apr-98                      1
10-Mar-82                      1
15-Jun-25                      1
27-May-28                      1
16-Aug-66                      1
12-Aug-07                      1
27-Mar-09                      1
Dec-86                         1
28-Oct-50                      1
03-Jul-14                      1
Before 1916                    1
19-Jan-05                      1
Name: Date, Length: 5128, dtype: int64

In [87]:
df_clean = pd.DataFrame(columns=[])

df_fechas["Date"] = df_cleaning["Date"].copy()
display(df_fechas.head())

# df_fechas["Case Number"][df_fechas.str.contains('^\d\d\d\d\.\d\d\.\d\d.*')]

columna_mes = []

def findmonth(m):
    if "Jan" in m or "jan" in m:
        return 1
    elif "Feb" in m or "feb" in m:
        return 2
    elif "Mar" in m or "mar" in m:
        return 3
    elif "Apr" in m or "apr" in m:
        return 4
    elif "May" in m or "may" in m:
        return 5
    elif "Jun" in m or "jun" in m:
        return 6
    elif "Jul" in m or "jul" in m:
        return 7
    elif "Aug" in m or "aug" in m:
        return 8
    elif "Sep" in m or "sep" in m:
        return 9
    elif "Oct" in m or "oct" in m:
        return 10
    elif "Nov" in m or "nov" in m:
        return 11
    elif "Dic" in m or "dic" in m:
        return 12
    else:
        return 0


'''for e in df_fechas["Date"]:
    #year = findyear()
    month = findmonth(e)
    
    columna_mes.append(month)
    #day = findday()
'''

df_fechas["month"] = df_fechas["Date"].apply(findmonth)
display(df_fechas["month"])

0    2016.09.18.c
1    2016.09.18.b
2    2016.09.18.a
3      2016.09.17
4      2016.09.15
Name: Case Number, dtype: object

0       9
1       9
2       9
3       9
4       9
5       9
6       9
7       9
8       9
9       9
10      9
11      9
12      9
13      8
14      8
15      8
16      8
17      8
18      8
19      8
20      7
21      7
22      7
23      7
24      7
25      7
26      7
27      7
28      7
29      7
       ..
5962    0
5963    0
5964    0
5965    0
5966    0
5967    0
5968    0
5969    0
5970    0
5971    0
5972    0
5973    0
5974    0
5975    0
5976    0
5977    0
5978    7
5979    7
5980    7
5981    0
5982    0
5983    0
5984    0
5985    0
5986    0
5987    0
5988    0
5989    0
5990    0
5991    0
Name: Date, Length: 5992, dtype: int64

In [102]:
x = df_cleaning[df_cleaning["Year"]==0]

x["Case Number"].head().value_counts()

0.0336     1
0.0725     1
ND-0153    1
0.0214     1
0.0493     1
Name: Case Number, dtype: int64

In [114]:
# TOMO LA DECISIÓN DE TRABAJAR

y = df_cleaning[df_cleaning["Year"]>1900]

y.head()

null_cols4 = y.isnull().sum()
print(y.shape)
null_cols4

(5311, 22)

Case Number                  0
Date                         0
Year                         0
Type                         0
Country                     22
Area                       295
Location                   363
Activity                   425
Name                       158
Sex                        504
Age                       2091
Injury                      19
Fatal (Y/N)                  9
Time                      2624
Species                   2377
Investigator or Source      13
pdf                          0
href formula                 1
href                         2
Case Number.1                0
Case Number.2                0
original order               0
dtype: int64

In [115]:
y = df_cleaning[df_cleaning["Year"]>1905]

y.head()

null_cols4 = y.isnull().sum()
print(y.shape)
null_cols4

(5248, 22)

Case Number                  0
Date                         0
Year                         0
Type                         0
Country                     22
Area                       290
Location                   356
Activity                   421
Name                       156
Sex                        502
Age                       2044
Injury                      18
Fatal (Y/N)                  8
Time                      2570
Species                   2322
Investigator or Source      13
pdf                          0
href formula                 1
href                         2
Case Number.1                0
Case Number.2                0
original order               0
dtype: int64

In [117]:
# TOMO LA DECISIÓN DE TRABAJAR CON DATOS A PARTIR DE 1900

df_cleaning = df_cleaning[df_cleaning["Year"]>1900]

null_cols4 = df_cleaning.isnull().sum()
print(df_cleaning.shape)
null_cols4

(5311, 22)

Case Number                  0
Date                         0
Year                         0
Type                         0
Country                     22
Area                       295
Location                   363
Activity                   425
Name                       158
Sex                        504
Age                       2091
Injury                      19
Fatal (Y/N)                  9
Time                      2624
Species                   2377
Investigator or Source      13
pdf                          0
href formula                 1
href                         2
Case Number.1                0
Case Number.2                0
original order               0
dtype: int64

In [132]:

columna_mes = []
#df_cleaning.drop("month", inplace=True, axis = 0)

def findmonth(m):
    if "Jan" in m or "jan" in m:
        return 1
    elif "Feb" in m or "feb" in m:
        return 2
    elif "Mar" in m or "mar" in m:
        return 3
    elif "Apr" in m or "apr" in m:
        return 4
    elif "May" in m or "may" in m:
        return 5
    elif "Jun" in m or "jun" in m:
        return 6
    elif "Jul" in m or "jul" in m:
        return 7
    elif "Aug" in m or "aug" in m:
        return 8
    elif "Sep" in m or "sep" in m:
        return 9
    elif "Oct" in m or "oct" in m:
        return 10
    elif "Nov" in m or "nov" in m:
        return 11
    elif "Dec" in m or "dec" in m:
        return 12
    else:
        return 0

df_cleaning["month"] = df_cleaning["Date"].apply(findmonth)
#display(df_cleaning["month"])


w = df_cleaning[df_cleaning["month"] == 0]
display(w.shape)

(285, 23)

In [133]:
df_cleaning.head()

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,...,Time,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,month
0,2016.09.18.c,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,male,M,...,13h00,NaN,"Orlando Sentinel, 9/19/2016",2016.09.18.c-NSB.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.18.c,2016.09.18.c,5993,9
1,2016.09.18.b,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,Chucky Luciano,M,...,11h00,NaN,"Orlando Sentinel, 9/19/2016",2016.09.18.b-Luciano.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.18.b,2016.09.18.b,5992,9
2,2016.09.18.a,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,male,M,...,10h43,NaN,"Orlando Sentinel, 9/19/2016",2016.09.18.a-NSB.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.18.a,2016.09.18.a,5991,9
3,2016.09.17,17-Sep-16,2016,Unprovoked,AUSTRALIA,Victoria,Thirteenth Beach,Surfing,Rory Angiolella,M,...,NaN,NaN,"The Age, 9/18/2016",2016.09.17-Angiolella.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.17,2016.09.17,5990,9
4,2016.09.15,16-Sep-16,2016,Unprovoked,AUSTRALIA,Victoria,Bells Beach,Surfing,male,M,...,NaN,2 m shark,"The Age, 9/16/2016",2016.09.16-BellsBeach.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.16,2016.09.15,5989,9

In [141]:
df_cleaning.drop(["original order"], axis = 1, inplace = True)

KeyError: "['original order'] not found in axis"

In [140]:
df_cleaning.head()

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,...,Fatal (Y/N),Time,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,month
0,2016.09.18.c,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,male,M,...,N,13h00,NaN,"Orlando Sentinel, 9/19/2016",2016.09.18.c-NSB.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.18.c,2016.09.18.c,9
1,2016.09.18.b,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,Chucky Luciano,M,...,N,11h00,NaN,"Orlando Sentinel, 9/19/2016",2016.09.18.b-Luciano.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.18.b,2016.09.18.b,9
2,2016.09.18.a,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,male,M,...,N,10h43,NaN,"Orlando Sentinel, 9/19/2016",2016.09.18.a-NSB.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.18.a,2016.09.18.a,9
3,2016.09.17,17-Sep-16,2016,Unprovoked,AUSTRALIA,Victoria,Thirteenth Beach,Surfing,Rory Angiolella,M,...,N,NaN,NaN,"The Age, 9/18/2016",2016.09.17-Angiolella.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.17,2016.09.17,9
4,2016.09.15,16-Sep-16,2016,Unprovoked,AUSTRALIA,Victoria,Bells Beach,Surfing,male,M,...,N,NaN,2 m shark,"The Age, 9/16/2016",2016.09.16-BellsBeach.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.16,2016.09.15,9

In [143]:
df_cleaning.drop(["Case Number.1", "Case Number.2"], axis = 1, inplace = True)

In [144]:
df_cleaning.head()

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Time,Species,Investigator or Source,pdf,href formula,href,month
0,2016.09.18.c,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,male,M,16,Minor injury to thigh,N,13h00,NaN,"Orlando Sentinel, 9/19/2016",2016.09.18.c-NSB.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,9
1,2016.09.18.b,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,Chucky Luciano,M,36,Lacerations to hands,N,11h00,NaN,"Orlando Sentinel, 9/19/2016",2016.09.18.b-Luciano.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,9
2,2016.09.18.a,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,male,M,43,Lacerations to lower leg,N,10h43,NaN,"Orlando Sentinel, 9/19/2016",2016.09.18.a-NSB.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,9
3,2016.09.17,17-Sep-16,2016,Unprovoked,AUSTRALIA,Victoria,Thirteenth Beach,Surfing,Rory Angiolella,M,NaN,Struck by fin on chest & leg,N,NaN,NaN,"The Age, 9/18/2016",2016.09.17-Angiolella.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,9
4,2016.09.15,16-Sep-16,2016,Unprovoked,AUSTRALIA,Victoria,Bells Beach,Surfing,male,M,NaN,No injury: Knocked off board by shark,N,NaN,2 m shark,"The Age, 9/16/2016",2016.09.16-BellsBeach.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,9

In [145]:
null_cols5 = df_cleaning.isnull().sum()
print(df_cleaning.shape)
null_cols5

(5311, 20)

Case Number                  0
Date                         0
Year                         0
Type                         0
Country                     22
Area                       295
Location                   363
Activity                   425
Name                       158
Sex                        504
Age                       2091
Injury                      19
Fatal (Y/N)                  9
Time                      2624
Species                   2377
Investigator or Source      13
pdf                          0
href formula                 1
href                         2
month                        0
dtype: int64

In [147]:
df_cleaning["Age"].value_counts()

17                         143
18                         139
20                         133
19                         132
16                         132
15                         127
21                         111
22                         109
24                         102
25                         100
14                          93
13                          84
23                          78
26                          77
27                          76
28                          75
29                          74
30                          72
12                          68
32                          64
35                          62
10                          51
31                          50
38                          47
40                          47
34                          45
43                          43
36                          40
33                          39
42                          36
                          ...
mid-30s                      1
Ca. 33                       1
25 or 28                     1
7      &    31               1
12 or 13                     1
31 or 33                     1
21, 34,24 & 35               1
Elderly                      1
Teens                        1
9 or 10                      1
?    &   14                  1
A.M.                         1
10 or 12                     1
1                            1
Â                            1
16 to 18                     1
36 & 26                      1
MAKE LINE GREEN              1
17 & 16                      1
23 & 20                      1
37, 67, 35, 27,  ? & 27      1
73                           1
36 & 23                      1
30 & 32                      1
28, 23 & 30                  1
81                           1
18 to 22                     1
23 & 26                      1
9 months                     1
72                           1
Name: Age, Length: 148, dtype: int64

In [153]:
df_cleaning['Age'].fillna(-1,inplace=True)
z = df_cleaning[df_cleaning["Age"].str.contains("&")==True]
print(z.shape)
display(z)

(22, 20)

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Time,Species,Investigator or Source,pdf,href formula,href,month
475,2013.03.10.a,10-Mar-13,2013,Unprovoked,PHILIPPINES,Palawan,Off Likas Island,Swimming to shore with floatioon devices after...,Alvin Lovido & John Paul Mangaoang,M,28 & 26,Minor leg injuries,N,NaN,"""small sharks""","E. Badilla, InterAksyon.com, 3/15/2013",2013.03.10.a-PhilippineMarines.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,3
1282,2006.01.28.R,Reported 28-Jan-2006,2006,Boat,ATLANTIC OCEAN,300 miles from Antigua,NaN,Competing in the Woodvale Atlantic Rowing Race,"Mayabrit, an ocean rowing boat. Occupants: And...",M,46 & 34,No injury to occupants; shark rammed boat repe...,N,NaN,12' shark,"N. Bevan, icwales.icnetwork.co.uk, 1/28/2006",2006.01.28.R-Mayabrit.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1
1284,2006.01.23,23-Jan-06,2006,Boat,ATLANTIC OCEAN,800 miles from land,NaN,Competing in the Woodvale Atlantic Rowing Race,"Rowgirls, an ocean rowing boat. Occupants: Sal...",F,"28, 23 & 30","No injury to occupants; a shark, accidentally ...",N,NaN,NaN,"Northants News, 1/25/2006",2006.01.23-Rowgirls.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1
1519,2003.09.14.b,14-Sep-03,2003,Boat,SOUTH AFRICA,Western Cape Province,Melkbosstrand,Fishing,"inflatable boat, occupants: Rudolf Bokelmann a...",NaN,36 & 26,"No injury to occupants, shark bit boat",N,09h40,2 m cow shark,"E. Ritter, GSAF",2003.09.14.b-CowShark.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,9
1701,2001.08.12,12-Aug-01,2001,Unprovoked,THAILAND,Rayong Province,Laem Mae Pim Beach,Fell off banana boat,O. Jaimaung & friend,M,21 & ?,Legs bitten,N,NaN,3 m [10'] shark,O. Jaimuang,2001.08.12-Jaimuang.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,8
1802,2000.08.10,10-Aug-00,2000,Invalid,USA,Florida,Florida Keys,Attempting to illegally enter the USA,Juan & Alex Bueno,M,23 & 20,Shark involvement probably post-mortem,Y,NaN,NaN,Press clippings,2000.08.10-BuenoBrothers.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,8
2197,1994.09.11.R,Reported 11-Sep-1994,1994,Sea Disaster,USA,Florida,Florida Straits,Adrift on refugee raft,2 Cuban brothers,M,7 & 31,FATAL,Y,NaN,NaN,"Sunday Herald Sun, 9/11/1994, p.25",1994.09.11.R-CubanRefugees.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,9
2286,1993.01.04,04-Jan-93,1993,Boat,CARIBBEAN SEA,NaN,Off Dominican Republic,,"canoe, occupants: Chris Newman & Stewart Newman",M,32 & 30,"No injury to occupants. Sharks, attracted to o...",N,NaN,Two 3 m [10'] oceanic whitetip sharks,"A. MacCormick, p.100",1993.01.04-DominicanRepublic.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1
3233,1968.08.24,24-Aug-68,1968,Unprovoked,USA,Florida,Half mile north of Juno Beach Pier,Playing with a frisbee in the shallows,Colleen Chamberlin & Scott Chamberlin,NaN,9 & 12,"Shark bumped Colleen, the nudged Scott, then b...",N,16h00,a small hammerhead shark,"M. Vorenberg, GSAF",1968.08.24-Chamberlin.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,8
3291,1967.08.10,10-Aug-67,1967,Invalid,AUSTRALIA,New South Wales,Jervis Bay,Anti-sabotage night dive exercise alongside de...,"J.T. Hales and Kenneth J. Hislop, Australian N...",M,? & 19,"Disappeared, no trace of men or equipment, sha...",Y,Night,NaN,"H.D. Baldridge, p.184",1967.08.10-Hales-Hislop.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,8
3516,1963.08.00,Aug-63,1963,Unprovoked,DOMINICAN REPUBLIC,Santo Domingo,Rio Haina Port,"Swimming, when caught in heavy seas",2 males,M,23 & 26,"FATAL. Eyewitness said, ""One was thrown in the...",Y,NaN,8 sharks,"A. Gigante, Jr; H.D. Baldridge; M. McDiarmid, ...",1963.08.00-2males.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,8
3654,1961.09.02.R,Reported 06-Sep-1961,1961,Provoked,ITALY,Venice Province,Chioggia,Fishing,Pollione Perrini & Fioravante Perini,M,33 & 37,Left foot & right hand bitten by netted shark ...,N,NaN,1 m shark,"C. Moore, GSAF",1961.09.06.R-Chioggia.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,9
3760,1960.06.07,07-Jun-60,1960,Invalid,USA,California,"10 miles off Santa Barbara, Santa Barbara County",Testing classified underwater electronic gear ...,"Paul Timothy Lovette, Dr. Neal Beardsley, Jame...",M,"37, 67, 35, 27, ? & 27","Legs & arms bitten, coroner unable to determin...",N,NaN,NaN,"L.A. Times, 6/10/1960; L. Schultz & M. Malin, ...",1960.06.07-Raytheon.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,6
3772,1960.04.14,14-Apr-60,1960,Invalid,BERMUDA,"33N, 68W",Royal Canadian Navy CS2F-1 aircraft ditched in...,Floating on a raft,"Crew of aircraft: McGreevy, Beakley, Rosenthal...",M,"21, 34,24 & 35","No injury, shark bumped raft",N,09h00 - 09h30,Five 1.8 m [6'] sharks,"G.S. Beakley, RCN; L. Schultz & M. Malin, p.55...",1960.04.14-Beakley-recheck text-March.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,4
3783,1960.02.29,29-Feb-60,1960,Unprovoked,AUSTRALIA,Tasmania,Ralph Bay,"Wading, fishing for flounder",Malcolm Robertson & Tom Hasler,M,30 & 32,"No injury, Robertson knocked over & Hasler bru...",N,Night,Two 2.1 m [7'] sharks,Hobart Mercury 3/3/1960,1960.02.29-Robertson-Hasler.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2
3809,1959.12.28,28-Dec-59,1959,Boat,AUSTRALIA,New South Wales,"Leichardt, Sydney",Fishing,"plywood dinghy, occupants: Jack Deegan & Trevo...",NaN,50 & 30,No injury to occupants,N,Late night,2.4 m [8'] shark,"Daily Mirror (Sydney), 12/29/1959",1959.12.28-NV-Deegan-dinghy.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,12
3813,1959.12.11,11-Dec-59,1959,Provoked,AUSTRALIA,Victoria,"Altona, Melbourne","Spearfishing, Smith & Walker touched shark wi...",Barry Smith & Harold Walker,M,17 & 35,"Smith hit by tail of shark, Walker sustained c...",N,NaN,2.7 m [9'] shark,"V.M. Coppleson (1962), p.252;",1959.12.11-Smith-Walker.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,12
3852,1959.08.02,21764,1959,Invalid,ITALY,Tuscany,"Cala del Corvo, Isola del Giglio",Scuba diving,Karl Pollerer & Eric Eisesenid,M,34 & 19,Probable drowing. Shark involvement unconfirmed,Y,NaN,NaN,"C. Moore, GSAF",1959.08.02-Giglio.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,0
3892,1959.01.02,02-Jan-59,1959,Unprovoked,MOZAMBIQUE,Maputo Province,Off Inhaca Island,Swimming ashore from fishing boat swamped and ...,Eric Suttie & Peter Murray,M,33 & 26,"Suttie's lower abdomen was bitten, Murray disa...",Y,08h00,NaN,"M. Levine, GSAF; Cape Argus 1/3/1959; Natal Me...",1959.01.02-Suttie.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1
4360,1947.01.14,14-Jan-47,1947,Boating,AUSTRALIA,New South Wales,"Berry's Bay, Sydney Harbour",Rowing,"rowboat, occupants: Bob Scott & John Blackwell",NaN,17 & 16,"No injury, shark lifted the boat 0.5 m out of ...",N,NaN,"4.5 m [14'9""] shark","A. Sharpe, p.73",1947.01.14-rowboat.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1
4769,1932.01.06,06-Jan-32,1932,Provoked,MEXICO,Baja California,Descano Point,Fishing,Efrain Ybarra & Francisco Durazzo,M,36 & 23,Hooked shark capsized rowboat & the 2 men were...,Y,NaN,NaN,"NY Herald Tribune, 1/8/1933",1932.01.06-BajaFishermen.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1
4950,1924.07.04,04-Jul-24,1924,Boating,USA,California,"Newport Beach, Orange County",Fishing,"18' boat, occupants Richard Gunther & Donald C...",M,? & 14,"No injury, shark tore hole in the side of the ...",N,NaN,NaN,"The Daily Pilot, 3/6/2010, citing The Times 7/...",1924.07.04-boat-NewportBeach.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,7

In [158]:
# BORRO LOS ATAQUES DE TYPE INVALID, POR QUE NO SON ATAQUES REALES
df_cleaning=df_cleaning[df_cleaning["Type"] != "Invalid"]

In [159]:
df_cleaning.shape

(4862, 20)

In [176]:
df_cleaning['Age'].fillna(-1,inplace=True)
z = df_cleaning[(df_cleaning["Age"].str.contains("&")==True) | (df_cleaning["Age"].str.contains("and")==True)]
print(z.shape)
display(z)

(17, 20)

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Time,Species,Investigator or Source,pdf,href formula,href,Month
475,2013.03.10.a,10-Mar-13,2013,Unprovoked,PHILIPPINES,Palawan,Off Likas Island,Swimming to shore with floatioon devices after...,Alvin Lovido & John Paul Mangaoang,M,28 & 26,Minor leg injuries,N,NaN,"""small sharks""","E. Badilla, InterAksyon.com, 3/15/2013",2013.03.10.a-PhilippineMarines.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,3
1282,2006.01.28.R,Reported 28-Jan-2006,2006,Boat,ATLANTIC OCEAN,300 miles from Antigua,NaN,Competing in the Woodvale Atlantic Rowing Race,"Mayabrit, an ocean rowing boat. Occupants: And...",M,46 & 34,No injury to occupants; shark rammed boat repe...,N,NaN,12' shark,"N. Bevan, icwales.icnetwork.co.uk, 1/28/2006",2006.01.28.R-Mayabrit.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1
1284,2006.01.23,23-Jan-06,2006,Boat,ATLANTIC OCEAN,800 miles from land,NaN,Competing in the Woodvale Atlantic Rowing Race,"Rowgirls, an ocean rowing boat. Occupants: Sal...",F,"28, 23 & 30","No injury to occupants; a shark, accidentally ...",N,NaN,NaN,"Northants News, 1/25/2006",2006.01.23-Rowgirls.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1
1519,2003.09.14.b,14-Sep-03,2003,Boat,SOUTH AFRICA,Western Cape Province,Melkbosstrand,Fishing,"inflatable boat, occupants: Rudolf Bokelmann a...",NaN,36 & 26,"No injury to occupants, shark bit boat",N,09h40,2 m cow shark,"E. Ritter, GSAF",2003.09.14.b-CowShark.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,9
1701,2001.08.12,12-Aug-01,2001,Unprovoked,THAILAND,Rayong Province,Laem Mae Pim Beach,Fell off banana boat,O. Jaimaung & friend,M,21 & ?,Legs bitten,N,NaN,3 m [10'] shark,O. Jaimuang,2001.08.12-Jaimuang.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,8
2197,1994.09.11.R,Reported 11-Sep-1994,1994,Sea Disaster,USA,Florida,Florida Straits,Adrift on refugee raft,2 Cuban brothers,M,7 & 31,FATAL,Y,NaN,NaN,"Sunday Herald Sun, 9/11/1994, p.25",1994.09.11.R-CubanRefugees.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,9
2286,1993.01.04,04-Jan-93,1993,Boat,CARIBBEAN SEA,NaN,Off Dominican Republic,,"canoe, occupants: Chris Newman & Stewart Newman",M,32 & 30,"No injury to occupants. Sharks, attracted to o...",N,NaN,Two 3 m [10'] oceanic whitetip sharks,"A. MacCormick, p.100",1993.01.04-DominicanRepublic.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1
3233,1968.08.24,24-Aug-68,1968,Unprovoked,USA,Florida,Half mile north of Juno Beach Pier,Playing with a frisbee in the shallows,Colleen Chamberlin & Scott Chamberlin,NaN,9 & 12,"Shark bumped Colleen, the nudged Scott, then b...",N,16h00,a small hammerhead shark,"M. Vorenberg, GSAF",1968.08.24-Chamberlin.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,8
3516,1963.08.00,Aug-63,1963,Unprovoked,DOMINICAN REPUBLIC,Santo Domingo,Rio Haina Port,"Swimming, when caught in heavy seas",2 males,M,23 & 26,"FATAL. Eyewitness said, ""One was thrown in the...",Y,NaN,8 sharks,"A. Gigante, Jr; H.D. Baldridge; M. McDiarmid, ...",1963.08.00-2males.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,8
3654,1961.09.02.R,Reported 06-Sep-1961,1961,Provoked,ITALY,Venice Province,Chioggia,Fishing,Pollione Perrini & Fioravante Perini,M,33 & 37,Left foot & right hand bitten by netted shark ...,N,NaN,1 m shark,"C. Moore, GSAF",1961.09.06.R-Chioggia.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,9
3783,1960.02.29,29-Feb-60,1960,Unprovoked,AUSTRALIA,Tasmania,Ralph Bay,"Wading, fishing for flounder",Malcolm Robertson & Tom Hasler,M,30 & 32,"No injury, Robertson knocked over & Hasler bru...",N,Night,Two 2.1 m [7'] sharks,Hobart Mercury 3/3/1960,1960.02.29-Robertson-Hasler.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2
3809,1959.12.28,28-Dec-59,1959,Boat,AUSTRALIA,New South Wales,"Leichardt, Sydney",Fishing,"plywood dinghy, occupants: Jack Deegan & Trevo...",NaN,50 & 30,No injury to occupants,N,Late night,2.4 m [8'] shark,"Daily Mirror (Sydney), 12/29/1959",1959.12.28-NV-Deegan-dinghy.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,12
3813,1959.12.11,11-Dec-59,1959,Provoked,AUSTRALIA,Victoria,"Altona, Melbourne","Spearfishing, Smith & Walker touched shark wi...",Barry Smith & Harold Walker,M,17 & 35,"Smith hit by tail of shark, Walker sustained c...",N,NaN,2.7 m [9'] shark,"V.M. Coppleson (1962), p.252;",1959.12.11-Smith-Walker.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,12
3892,1959.01.02,02-Jan-59,1959,Unprovoked,MOZAMBIQUE,Maputo Province,Off Inhaca Island,Swimming ashore from fishing boat swamped and ...,Eric Suttie & Peter Murray,M,33 & 26,"Suttie's lower abdomen was bitten, Murray disa...",Y,08h00,NaN,"M. Levine, GSAF; Cape Argus 1/3/1959; Natal Me...",1959.01.02-Suttie.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1
4360,1947.01.14,14-Jan-47,1947,Boating,AUSTRALIA,New South Wales,"Berry's Bay, Sydney Harbour",Rowing,"rowboat, occupants: Bob Scott & John Blackwell",NaN,17 & 16,"No injury, shark lifted the boat 0.5 m out of ...",N,NaN,"4.5 m [14'9""] shark","A. Sharpe, p.73",1947.01.14-rowboat.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1
4769,1932.01.06,06-Jan-32,1932,Provoked,MEXICO,Baja California,Descano Point,Fishing,Efrain Ybarra & Francisco Durazzo,M,36 & 23,Hooked shark capsized rowboat & the 2 men were...,Y,NaN,NaN,"NY Herald Tribune, 1/8/1933",1932.01.06-BajaFishermen.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1
4950,1924.07.04,04-Jul-24,1924,Boating,USA,California,"Newport Beach, Orange County",Fishing,"18' boat, occupants Richard Gunther & Donald C...",M,? & 14,"No injury, shark tore hole in the side of the ...",N,NaN,NaN,"The Daily Pilot, 3/6/2010, citing The Times 7/...",1924.07.04-boat-NewportBeach.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,7

In [166]:
df_cleaning["Sex "].value_counts()

M      3919
F       495
M         2
lli       1
.         1
N         1
Name: Sex , dtype: int64

In [169]:
df_cleaning.rename(index=str, columns={"Sex ": "Sex", "month": "Month", "Species ": "Species"}, inplace = True)

In [171]:
df_cleaning["Species"].value_counts()

White shark                                                                                                                                           149
Tiger shark                                                                                                                                            58
Bull shark                                                                                                                                             45
4' shark                                                                                                                                               39
6' shark                                                                                                                                               37
1.8 m [6'] shark                                                                                                                                       33
1.5 m [5'] shark                                                                                                                                       31
1.2 m [4'] shark                                                                                                                                       26
3' shark                                                                                                                                               24
5' shark                                                                                                                                               23
4' to 5' shark                                                                                                                                         22
Wobbegong shark                                                                                                                                        20
2 m shark                                                                                                                                              20
3 m [10'] shark                                                                                                                                        20
3' to 4' shark                                                                                                                                         18
3 m shark                                                                                                                                              16
2.4 m [8'] shark                                                                                                                                       16
Blacktip shark                                                                                                                                         14
1.2 m to 1.5 m [4' to 5'] shark                                                                                                                        14
3.7 m [12'] shark                                                                                                                                      14
Blue shark                                                                                                                                             14
Mako shark                                                                                                                                             13
"a small shark"                                                                                                                                        13
Raggedtooth shark                                                                                                                                      12
Bronze whaler shark                                                                                                                                    12
1.5 m shark                                                                                                                                            12
6 m [20'] white shark                                                                                                                                  12
5 m [16.5'] white shark                                                                                                                                12
Nurse shark                                                                                                                                            11
Zambesi shark                                                                                                                                          11
                                                                                                                                                     ...
Tiger shark, 3.7 m to 4.5 m [12' to 14'9"]                                                                                                              1
Tooth fragments recovered from hull                                                                                                                     1
Sandbar shark ,8'                                                                                                                                       1
Tiger shark, 3m                                                                                                                                         1
1.5 m grey reef shark                                                                                                                                   1
7' silvertip shark                                                                                                                                      1
White shark, 3m, seen in area and hooked 3 days later                                                                                                   1
Thought to involve a juvenile hammerhead shark                                                                                                          1
4 m [13'] shark seen in vicinity                                                                                                                        1
4' spinner shark                                                                                                                                        1
White shark, 7m                                                                                                                                         1
Bull shark, 10'                                                                                                                                         1
Thought to involve a 2.4 m [8'] lemon shark; two 2.4 m lemon sharks caught within 100 yds of the site a week prior to & a week after this incident      1
4.5 m to 5.5 m [14.7' to 18'] white shark                                                                                                               1
White shark, 2 m                                                                                                                                        1
Tawny nurse shark                                                                                                                                       1
Nurse shark, juvenile                                                                                                                                   1
White shark, 16'                                                                                                                                        1
Tiger shark, 2.5 m [8.25']                                                                                                                              1
>1.6 m shark                                                                                                                                            1
Tooth fragments of âwhalerâ shark were recovered, a bull shark, according to Edwards                                                                1
White shark, 2.7 m [9'], 280-lb                                                                                                                         1
20 kg shark                                                                                                                                             1
Wobbegong shark, 1m                                                                                                                                     1
Tiger shark, 2m                                                                                                                                         1
White shark, 4 to 5 m                                                                                                                                   1
Tiger shark, 13'                                                                                                                                        1
"Blue whaler" (Galeolamna)                                                                                                                              1
7' to 8' shark                                                                                                                                          1
a "small slim brown shark"                                                                                                                              1
Name: Species, Length: 1407, dtype: int64

In [172]:
df_cleaning.columns

Index(['Case Number', 'Date', 'Year', 'Type', 'Country', 'Area', 'Location',
       'Activity', 'Name', 'Sex', 'Age', 'Injury', 'Fatal (Y/N)', 'Time',
       'Species', 'Investigator or Source', 'pdf', 'href formula', 'href',
       'Month'],
      dtype='object')

In [173]:
#df_ages = pd.DataFrame(columns=df_cleaning.columns)
#display(df_ages)

Empty DataFrame
Columns: [Case Number, Date, Year, Type, Country, Area, Location, Activity, Name, Sex, Age, Injury, Fatal (Y/N), Time, Species, Investigator or Source, pdf, href formula, href, Month]
Index: []

In [195]:
df_ages = pd.DataFrame(columns=df_cleaning.columns)

import re
import math

for e in z["Age"]:
    ages = re.findall(r"[\d]+", e)
    for q in ages:
        df_ages = pd.concat([df_ages, z[z["Age"]==e]], ignore_index = True)
        df_ages["Age"][df_ages.index.max()] = q

display (df_ages)

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Time,Species,Investigator or Source,pdf,href formula,href,Month
0,2013.03.10.a,10-Mar-13,2013,Unprovoked,PHILIPPINES,Palawan,Off Likas Island,Swimming to shore with floatioon devices after...,Alvin Lovido & John Paul Mangaoang,M,28,Minor leg injuries,N,NaN,"""small sharks""","E. Badilla, InterAksyon.com, 3/15/2013",2013.03.10.a-PhilippineMarines.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,3
1,2013.03.10.a,10-Mar-13,2013,Unprovoked,PHILIPPINES,Palawan,Off Likas Island,Swimming to shore with floatioon devices after...,Alvin Lovido & John Paul Mangaoang,M,26,Minor leg injuries,N,NaN,"""small sharks""","E. Badilla, InterAksyon.com, 3/15/2013",2013.03.10.a-PhilippineMarines.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,3
2,2006.01.28.R,Reported 28-Jan-2006,2006,Boat,ATLANTIC OCEAN,300 miles from Antigua,NaN,Competing in the Woodvale Atlantic Rowing Race,"Mayabrit, an ocean rowing boat. Occupants: And...",M,46,No injury to occupants; shark rammed boat repe...,N,NaN,12' shark,"N. Bevan, icwales.icnetwork.co.uk, 1/28/2006",2006.01.28.R-Mayabrit.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1
3,2006.01.28.R,Reported 28-Jan-2006,2006,Boat,ATLANTIC OCEAN,300 miles from Antigua,NaN,Competing in the Woodvale Atlantic Rowing Race,"Mayabrit, an ocean rowing boat. Occupants: And...",M,34,No injury to occupants; shark rammed boat repe...,N,NaN,12' shark,"N. Bevan, icwales.icnetwork.co.uk, 1/28/2006",2006.01.28.R-Mayabrit.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1
4,2006.01.23,23-Jan-06,2006,Boat,ATLANTIC OCEAN,800 miles from land,NaN,Competing in the Woodvale Atlantic Rowing Race,"Rowgirls, an ocean rowing boat. Occupants: Sal...",F,28,"No injury to occupants; a shark, accidentally ...",N,NaN,NaN,"Northants News, 1/25/2006",2006.01.23-Rowgirls.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1
5,2006.01.23,23-Jan-06,2006,Boat,ATLANTIC OCEAN,800 miles from land,NaN,Competing in the Woodvale Atlantic Rowing Race,"Rowgirls, an ocean rowing boat. Occupants: Sal...",F,23,"No injury to occupants; a shark, accidentally ...",N,NaN,NaN,"Northants News, 1/25/2006",2006.01.23-Rowgirls.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1
6,2006.01.23,23-Jan-06,2006,Boat,ATLANTIC OCEAN,800 miles from land,NaN,Competing in the Woodvale Atlantic Rowing Race,"Rowgirls, an ocean rowing boat. Occupants: Sal...",F,30,"No injury to occupants; a shark, accidentally ...",N,NaN,NaN,"Northants News, 1/25/2006",2006.01.23-Rowgirls.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1
7,2003.09.14.b,14-Sep-03,2003,Boat,SOUTH AFRICA,Western Cape Province,Melkbosstrand,Fishing,"inflatable boat, occupants: Rudolf Bokelmann a...",NaN,36,"No injury to occupants, shark bit boat",N,09h40,2 m cow shark,"E. Ritter, GSAF",2003.09.14.b-CowShark.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,9
8,2003.09.14.b,14-Sep-03,2003,Boat,SOUTH AFRICA,Western Cape Province,Melkbosstrand,Fishing,"inflatable boat, occupants: Rudolf Bokelmann a...",NaN,26,"No injury to occupants, shark bit boat",N,09h40,2 m cow shark,"E. Ritter, GSAF",2003.09.14.b-CowShark.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,9
9,2001.08.12,12-Aug-01,2001,Unprovoked,THAILAND,Rayong Province,Laem Mae Pim Beach,Fell off banana boat,O. Jaimaung & friend,M,21,Legs bitten,N,NaN,3 m [10'] shark,O. Jaimuang,2001.08.12-Jaimuang.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,8
10,1994.09.11.R,Reported 11-Sep-1994,1994,Sea Disaster,USA,Florida,Florida Straits,Adrift on refugee raft,2 Cuban brothers,M,7,FATAL,Y,NaN,NaN,"Sunday Herald Sun, 9/11/1994, p.25",1994.09.11.R-CubanRefugees.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,9
11,1994.09.11.R,Reported 11-Sep-1994,1994,Sea Disaster,USA,Florida,Florida Straits,Adrift on refugee raft,2 Cuban brothers,M,31,FATAL,Y,NaN,NaN,"Sunday Herald Sun, 9/11/1994, p.25",1994.09.11.R-CubanRefugees.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,9
12,1993.01.04,04-Jan-93,1993,Boat,CARIBBEAN SEA,NaN,Off Dominican Republic,,"canoe, occupants: Chris Newman & Stewart Newman",M,32,"No injury to occupants. Sharks, attracted to o...",N,NaN,Two 3 m [10'] oceanic whitetip sharks,"A. MacCormick, p.100",1993.01.04-DominicanRepublic.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1
13,1993.01.04,04-Jan-93,1993,Boat,CARIBBEAN SEA,NaN,Off Dominican Republic,,"canoe, occupants: Chris Newman & Stewart Newman",M,30,"No injury to occupants. Sharks, attracted to o...",N,NaN,Two 3 m [10'] oceanic whitetip sharks,"A. MacCormick, p.100",1993.01.04-DominicanRepublic.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1
14,1968.08.24,24-Aug-68,1968,Unprovoked,USA,Florida,Half mile north of Juno Beach Pier,Playing with a frisbee in the shallows,Colleen Chamberlin & Scott Chamberlin,NaN,9,"Shark bumped Colleen, the nudged Scott, then b...",N,16h00,a small hammerhead shark,"M. Vorenberg, GSAF",1968.08.24-Chamberlin.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,8
15,1968.08.24,24-Aug-68,1968,Unprovoked,USA,Florida,Half mile north of Juno Beach Pier,Playing with a frisbee in the shallows,Colleen Chamberlin & Scott Chamberlin,NaN,12,"Shark bumped Colleen, the nudged Scott, then b...",N,16h00,a small hammerhead shark,"M. Vorenberg, GSAF",1968.08.24-Chamberlin.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,8
16,1963.08.00,Aug-63,1963,Unprovoked,DOMINICAN REPUBLIC,Santo Domingo,Rio Haina Port,"Swimming, when caught in heavy seas",2 males,M,23,"FATAL. Eyewitness said, ""One was thrown in the...",Y,NaN,8 sharks,"A. Gigante, Jr; H.D. Baldridge; M. McDiarmid, ...",1963.08.00-2males.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,8
17,1963.08.00,Aug-63,1963,Unprovoked,DOMINICAN REPUBLIC,Santo Domingo,Rio Haina Port,"Swimming, when caught in heavy seas",2 males,M,26,"FATAL. Eyewitness said, ""One was thrown in the...",Y,NaN,8 sharks,"A. Gigante, Jr; H.D. Baldridge; M. McDiarmid, ...",1963.08.00-2males.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,8
18,1961.09.02.R,Reported 06-Sep-1961,1961,Provoked,ITALY,Venice Province,Chioggia,Fishing,Pollione Perrini & Fioravante Perini,M,33,Left foot & right hand bitten by netted shark ...,N,NaN,1 m shark,"C. Moore, GSAF",1961.09.06.R-Chioggia.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,9
19,1961.09.02.R,Reported 06-Sep-1961,1961,Provoked,ITALY,Venice Province,Chioggia,Fishing,Pollione Perrini & Fioravante Perini,M,37,Left foot & right hand bitten by netted shark ...,N,NaN,1 m shark,"C. Moore, GSAF",1961.09.06.R-Chioggia.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,9
20,1960.02.29,29-Feb-60,1960,Unprovoked,AUSTRALIA,Tasmania,Ralph Bay,"Wading, fishing for flounder",Malcolm Robertson & Tom Hasler,M,30,"No injury, Robertson knocked over & Hasler bru...",N,Night,Two 2.1 m [7'] sharks,Hobart Mercury 3/3/1960,1960.02.29-Robertson-Hasler.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2
21,1960.02.29,29-Feb-60,1960,Unprovoked,AUSTRALIA,Tasmania,Ralph Bay,"Wading, fishing for flounder",Malcolm Robertson & Tom Hasler,M,32,"No injury, Robertson knocked over & Hasler bru...",N,Night,Two 2.1 m [7'] sharks,Hobart Mercury 3/3/1960,1960.02.29-Robertson-Hasler.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2
22,1959.12.28,28-Dec-59,1959,Boat,AUSTRALIA,New South Wales,"Leichardt, Sydney",Fishing,"plywood dinghy, occupants: Jack Deegan & Trevo...",NaN,50,No injury to occupants,N,Late night,2.4 m [8'] shark,"Daily Mirror (Sydney), 12/29/1959",1959.12.28-NV-Deegan-dinghy.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,12
23,1959.12.28,28-Dec-59,1959,Boat,AUSTRALIA,New South Wales,"Leichardt, Sydney",Fishing,"plywood dinghy, occupants: Jack Deegan & Trevo...",NaN,30,No injury to occupants,N,Late night,2.4 m [8'] shark,"Daily Mirror (Sydney), 12/29/1959",1959.12.28-NV-Deegan-dinghy.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,12
24,1959.12.11,11-Dec-59,1959,Provoked,AUSTRALIA,Victoria,"Altona, Melbourne","Spearfishing, Smith & Walker touched shark wi...",Barry Smith & Harold Walker,M,17,"Smith hit by tail of shark, Walker sustained c...",N,NaN,2.7 m [9'] shark,"V.M. Coppleson (1962), p.252;",1959.12.11-Smith-Walker.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,12
25,1959.12.11,11-Dec-59,1959,Provoked,AUSTRALIA,Victoria,"Altona, Melbourne","Spearfishing, Smith & Walker touched shark wi...",Barry Smith & Harold Walker,M,35,"Smith hit by tail of shark, Walker sustained c...",N,NaN,2.7 m [9'] shark,"V.M. Coppleson (1962), p.252;",1959.12.11-Smith-Walker.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,12
26,1959.01.02,02-Jan-59,1959,Unprovoked,MOZAMBIQUE,Maputo Province,Off Inhaca Island,Swimming ashore from fishing boat swamped and ...,Eric Suttie & Peter Murray,M,33,"Suttie's lower abdomen was bitten, Murray disa...",Y,08h00,NaN,"M. Levine, GSAF; Cape Argus 1/3/1959; Natal Me...",1959.01.02-Suttie.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1
27,1959.01.02,02-Jan-59,1959,Unprovoked,MOZAMBIQUE,Maputo Province,Off Inhaca Island,Swimming ashore from fishing boat swamped and ...,Eric Suttie & Peter Murray,M,26,"Suttie's lower abdomen was bitten, Murray disa...",Y,08h00,NaN,"M. Levine, GSAF; Cape Argus 1/3/1959; Natal Me...",1959.01.02-Suttie.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1
28,1947.01.14,14-Jan-47,1947,Boating,AUSTRALIA,New South Wales,"Berry's Bay, Sydney Harbour",Rowing,"rowboat, occupants: Bob Scott & John Blackwell",NaN,17,"No injury, shark lifted the boat 0.5 m out of ...",N,NaN,"4.5 m [14'9""] shark","A. Sharpe, p.73",1947.01.14-rowboat.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1
29,1947.01.14,14-Jan-47,1947,Boating,AUSTRALIA,New South Wales,"Berry's Bay, Sydney Harbour",Rowing,"rowboat, occupants: Bob Scott & John Blackwell",NaN,16,"No injury, shark lifted the boat 0.5 m out of ...",N,NaN,"4.5 m [14'9""] shark","A. Sharpe, p.73",1947.01.14-rowboat.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1
30,1932.01.06,06-Jan-32,1932,Provoked,MEXICO,Baja California,Descano Point,Fishing,Efrain Ybarra & Francisco Durazzo,M,36,Hooked shark capsized rowboat & the 2 men were...,Y,NaN,NaN,"NY Herald Tribune, 1/8/1933",1932.01.06-BajaFishermen.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1
31,1932.01.06,06-Jan-32,1932,Provoked,MEXICO,Baja California,Descano Point,Fishing,Efrain Ybarra & Francisco Durazzo,M,23,Hooked shark capsized rowboat & the 2 men were...,Y,NaN,NaN,"NY Herald Tribune, 1/8/1933",1932.01.06-BajaFishermen.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1
32,1924.07.04,04-Jul-24,1924,Boating,USA,California,"Newport Beach, Orange County",Fishing,"18' boat, occupants Richard Gunther & Donald C...",M,14,"No injury, shark tore hole in the side of the ...",N,NaN,NaN,"The Daily Pilot, 3/6/2010, citing The Times 7/...",1924.07.04-boat-NewportBeach.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,7

In [201]:
df_cleaning = df_cleaning[(df_cleaning["Age"].str.contains("&")!=True)]
print(df_cleaning.shape)
#df_cleaning = pd.concat([df_cleaning, df_ages], ignore_index = True)
print(df_cleaning.shape)

(4845, 20)
(4878, 20)

In [202]:
display(df_cleaning.head())

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Time,Species,Investigator or Source,pdf,href formula,href,Month
0,2016.09.18.c,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,male,M,16,Minor injury to thigh,N,13h00,NaN,"Orlando Sentinel, 9/19/2016",2016.09.18.c-NSB.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,9
1,2016.09.18.b,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,Chucky Luciano,M,36,Lacerations to hands,N,11h00,NaN,"Orlando Sentinel, 9/19/2016",2016.09.18.b-Luciano.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,9
2,2016.09.18.a,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,male,M,43,Lacerations to lower leg,N,10h43,NaN,"Orlando Sentinel, 9/19/2016",2016.09.18.a-NSB.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,9
3,2016.09.17,17-Sep-16,2016,Unprovoked,AUSTRALIA,Victoria,Thirteenth Beach,Surfing,Rory Angiolella,M,-1,Struck by fin on chest & leg,N,NaN,NaN,"The Age, 9/18/2016",2016.09.17-Angiolella.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,9
4,2016.09.15,16-Sep-16,2016,Unprovoked,AUSTRALIA,Victoria,Bells Beach,Surfing,male,M,-1,No injury: Knocked off board by shark,N,NaN,2 m shark,"The Age, 9/16/2016",2016.09.16-BellsBeach.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,9