In [1]:
import pandas as pd

df = pd.read_csv("./GSAF5.csv", encoding="latin1")
display(df.head())

print(df.columns)
print(df.shape)

null_cols = df.isnull().sum()
print(null_cols)

display(df[df["Unnamed: 22"].isnull() == False])
display(df[df["Unnamed: 23"].isnull() == False])

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,...,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23
0,2016.09.18.c,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,male,M,...,NaN,"Orlando Sentinel, 9/19/2016",2016.09.18.c-NSB.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.18.c,2016.09.18.c,5993,NaN,NaN
1,2016.09.18.b,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,Chucky Luciano,M,...,NaN,"Orlando Sentinel, 9/19/2016",2016.09.18.b-Luciano.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.18.b,2016.09.18.b,5992,NaN,NaN
2,2016.09.18.a,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,male,M,...,NaN,"Orlando Sentinel, 9/19/2016",2016.09.18.a-NSB.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.18.a,2016.09.18.a,5991,NaN,NaN
3,2016.09.17,17-Sep-16,2016,Unprovoked,AUSTRALIA,Victoria,Thirteenth Beach,Surfing,Rory Angiolella,M,...,NaN,"The Age, 9/18/2016",2016.09.17-Angiolella.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.17,2016.09.17,5990,NaN,NaN
4,2016.09.15,16-Sep-16,2016,Unprovoked,AUSTRALIA,Victoria,Bells Beach,Surfing,male,M,...,2 m shark,"The Age, 9/16/2016",2016.09.16-BellsBeach.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.16,2016.09.15,5989,NaN,NaN

Index(['Case Number', 'Date', 'Year', 'Type', 'Country', 'Area', 'Location',
       'Activity', 'Name', 'Sex ', 'Age', 'Injury', 'Fatal (Y/N)', 'Time',
       'Species ', 'Investigator or Source', 'pdf', 'href formula', 'href',
       'Case Number.1', 'Case Number.2', 'original order', 'Unnamed: 22',
       'Unnamed: 23'],
      dtype='object')
(5992, 24)
Case Number                  0
Date                         0
Year                         0
Type                         0
Country                     43
Area                       402
Location                   496
Activity                   527
Name                       200
Sex                        567
Age                       2681
Injury                      27
Fatal (Y/N)                 19
Time                      3213
Species                   2934
Investigator or Source      15
pdf                          0
href formula                 1
href                         3
Case Number.1                0
Case Number.2                0
original order               0
Unnamed: 22               5991
Unnamed: 23               5990
dtype: int64

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,...,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23
1247,2006.06.18,18-Jun-06,2006,Unprovoked,BRAZIL,Pernambuco,"Punta Del Chifre Beach, Olinda",Body boarding,Humberto Pessoa Batista,M,...,NaN,globalsurfnews.com,2006.06.18-Batista.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2006.06.18,2006.06.18,4746,stopped here,NaN

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,...,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23
4182,1952.07.13,13-Jul-52,1952,Provoked,USA,California,"San Diego, San Diego County",Fishing,"Gerald Howard, on board sportsfishing boat Ter...",M,...,NaN,"L.A. Times, 7/14/1952",1952.07.13-Howard.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1952.07.13,1952.07.13,1811,NaN,Teramo
5585,1879.03.10,10-Mar-1879,1879,Invalid,AUSTRALIA,New South Wales,Near Sydney,The steamship Bonnie Dundee lost in collision,Cabin boy of the Bonnie Dundee,M,...,NaN,"Star, 3/22/1879",1879.03.10-Bonnie-Dundee.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1879.03.10,1879.03.10,408,NaN,change filename

He comprobado que las columnas sin nombre estÃ¡n vacÃ­as y las 3 que tienen informaciÃ³n, no son relevantes.

In [2]:
drop_cols = list(null_cols[null_cols > 5900].index)
df_cleaning = df.drop(drop_cols, axis = 1).copy()
# df_cleaning = df_cleaning.drop(["pdf", "href formula", "href"], axis = 1).copy()

df_cleaning.head()

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,...,Fatal (Y/N),Time,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order
0,2016.09.18.c,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,male,M,...,N,13h00,NaN,"Orlando Sentinel, 9/19/2016",2016.09.18.c-NSB.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.18.c,2016.09.18.c,5993
1,2016.09.18.b,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,Chucky Luciano,M,...,N,11h00,NaN,"Orlando Sentinel, 9/19/2016",2016.09.18.b-Luciano.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.18.b,2016.09.18.b,5992
2,2016.09.18.a,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,male,M,...,N,10h43,NaN,"Orlando Sentinel, 9/19/2016",2016.09.18.a-NSB.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.18.a,2016.09.18.a,5991
3,2016.09.17,17-Sep-16,2016,Unprovoked,AUSTRALIA,Victoria,Thirteenth Beach,Surfing,Rory Angiolella,M,...,N,NaN,NaN,"The Age, 9/18/2016",2016.09.17-Angiolella.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.17,2016.09.17,5990
4,2016.09.15,16-Sep-16,2016,Unprovoked,AUSTRALIA,Victoria,Bells Beach,Surfing,male,M,...,N,NaN,2 m shark,"The Age, 9/16/2016",2016.09.16-BellsBeach.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.16,2016.09.15,5989

Por otra parte, las columnas con los enlaces a los pdf, aunque algunos refieren a errores 404, pueden ser valiosos. Contienen informaciÃ³n que en ocasiones no ha sido introducida en la dataset. Para no repasar los 6000 datos, voy a
repasar si la informaciÃ³n que contienen es Ãºtil en los casos que los nulos sean menor que 50, para completar dicha informaciÃ³n.

In [3]:
null_cols = df.isnull().sum()
null_cols[(null_cols < 50) & (null_cols > 0)]

Country                   43
Injury                    27
Fatal (Y/N)               19
Investigator or Source    15
href formula               1
href                       3
dtype: int64

In [4]:
null_cols_2 = df[["Country", "Injury", "Fatal (Y/N)", "Investigator or Source"]].isnull().copy()
display(null_cols_2)

      Country  Injury  Fatal (Y/N)  Investigator or Source
0       False   False        False                   False
1       False   False        False                   False
2       False   False        False                   False
3       False   False        False                   False
4       False   False        False                   False
5       False   False        False                   False
6       False   False        False                   False
7       False   False        False                   False
8       False   False        False                   False
9       False   False        False                   False
10      False   False        False                   False
11      False   False        False                   False
12      False   False        False                   False
13      False   False        False                   False
14      False   False        False                   False
15      False   False        False                   False
16      False   False        False                   False
17      False   False        False                   False
18      False   False        False                   False
19      False   False        False                   False
20      False   False        False                   False
21      False   False        False                   False
22      False   False        False                   False
23      False   False        False                   False
24      False   False        False                   False
25      False   False        False                   False
26      False   False        False                   False
27      False   False        False                   False
28      False   False        False                   False
29      False   False        False                   False
...       ...     ...          ...                     ...
5962    False   False        False                   False
5963    False   False        False                   False
5964    False   False        False                   False
5965    False   False        False                   False
5966    False   False        False                   False
5967    False    True        False                   False
5968    False   False        False                   False
5969    False   False        False                   False
5970    False   False        False                   False
5971    False   False        False                   False
5972    False   False        False                   False
5973    False   False        False                   False
5974    False   False        False                   False
5975    False   False        False                   False
5976    False   False        False                   False
5977    False   False        False                   False
5978    False   False        False                   False
5979    False   False        False                   False
5980    False   False        False                   False
5981    False   False        False                   False
5982    False   False        False                   False
5983    False   False        False                   False
5984    False   False        False                   False
5985    False   False        False                   False
5986    False   False        False                   False
5987    False   False        False                   False
5988    False   False        False                   False
5989    False   False        False                   False
5990    False   False        False                   False
5991    False   False        False                   False

[5992 rows x 4 columns]

In [5]:
df_cleaning["Time"].value_counts()

Afternoon                 174
11h00                     123
12h00                     107
Morning                   107
15h00                     100
16h00                      94
14h00                      93
16h30                      72
13h00                      71
14h30                      70
17h30                      69
17h00                      64
18h00                      62
15h30                      62
11h30                      60
Night                      58
13h30                      56
10h00                      53
09h00                      46
10h30                      45
Evening                    33
12h30                      33
Late afternoon             32
07h30                      30
09h30                      30
08h00                      28
18h30                      27
08h30                      25
19h00                      23
07h00                      20
                         ...
17h00 Sunset                1
13h345                      1
11h00 / 11h30               1
2 hours after Opperman      1
17h42                       1
 14h00                      1
07h10                       1
19h28                       1
"After dark"                1
After midnight              1
06h00 -- 07h00              1
01h50                       1
09h30 / 10h00               1
>06h45                      1
Noon                        1
17h40                       1
Shortly before 13h00        1
18h30 (Sunset)              1
09h30 / 15h30               1
13h42                       1
10h22                       1
19h00-20h00                 1
11h48                       1
17h01                       1
12h39                       1
09h20                       1
11h25                       1
06h10                       1
16h25                       1
"Just before 11h00"         1
Name: Time, Length: 357, dtype: int64

In [6]:
display(df_cleaning["href formula"])

0       http://sharkattackfile.net/spreadsheets/pdf_di...
1       http://sharkattackfile.net/spreadsheets/pdf_di...
2       http://sharkattackfile.net/spreadsheets/pdf_di...
3       http://sharkattackfile.net/spreadsheets/pdf_di...
4       http://sharkattackfile.net/spreadsheets/pdf_di...
5       http://sharkattackfile.net/spreadsheets/pdf_di...
6       http://sharkattackfile.net/spreadsheets/pdf_di...
7       http://sharkattackfile.net/spreadsheets/pdf_di...
8       http://sharkattackfile.net/spreadsheets/pdf_di...
9       http://sharkattackfile.net/spreadsheets/pdf_di...
10      http://sharkattackfile.net/spreadsheets/pdf_di...
11      http://sharkattackfile.net/spreadsheets/pdf_di...
12      http://sharkattackfile.net/spreadsheets/pdf_di...
13      http://sharkattackfile.net/spreadsheets/pdf_di...
14      http://sharkattackfile.net/spreadsheets/pdf_di...
15      http://sharkattackfile.net/spreadsheets/pdf_di...
16      http://sharkattackfile.net/spreadsheets/pdf_di...
17      http://sharkattackfile.net/spreadsheets/pdf_di...
18      http://sharkattackfile.net/spreadsheets/pdf_di...
19      http://sharkattackfile.net/spreadsheets/pdf_di...
20      http://sharkattackfile.net/spreadsheets/pdf_di...
21      http://sharkattackfile.net/spreadsheets/pdf_di...
22      http://sharkattackfile.net/spreadsheets/pdf_di...
23      http://sharkattackfile.net/spreadsheets/pdf_di...
24      http://sharkattackfile.net/spreadsheets/pdf_di...
25      http://sharkattackfile.net/spreadsheets/pdf_di...
26      http://sharkattackfile.net/spreadsheets/pdf_di...
27      http://sharkattackfile.net/spreadsheets/pdf_di...
28      http://sharkattackfile.net/spreadsheets/pdf_di...
29      http://sharkattackfile.net/spreadsheets/pdf_di...
                              ...
5962    http://sharkattackfile.net/spreadsheets/pdf_di...
5963    http://sharkattackfile.net/spreadsheets/pdf_di...
5964    http://sharkattackfile.net/spreadsheets/pdf_di...
5965    http://sharkattackfile.net/spreadsheets/pdf_di...
5966    http://sharkattackfile.net/spreadsheets/pdf_di...
5967    http://sharkattackfile.net/spreadsheets/pdf_di...
5968    http://sharkattackfile.net/spreadsheets/pdf_di...
5969    http://sharkattackfile.net/spreadsheets/pdf_di...
5970    http://sharkattackfile.net/spreadsheets/pdf_di...
5971    http://sharkattackfile.net/spreadsheets/pdf_di...
5972    http://sharkattackfile.net/spreadsheets/pdf_di...
5973    http://sharkattackfile.net/spreadsheets/pdf_di...
5974    http://sharkattackfile.net/spreadsheets/pdf_di...
5975    http://sharkattackfile.net/spreadsheets/pdf_di...
5976    http://sharkattackfile.net/spreadsheets/pdf_di...
5977    http://sharkattackfile.net/spreadsheets/pdf_di...
5978    http://sharkattackfile.net/spreadsheets/pdf_di...
5979    http://sharkattackfile.net/spreadsheets/pdf_di...
5980    http://sharkattackfile.net/spreadsheets/pdf_di...
5981    http://sharkattackfile.net/spreadsheets/pdf_di...
5982    http://sharkattackfile.net/spreadsheets/pdf_di...
5983    http://sharkattackfile.net/spreadsheets/pdf_di...
5984    http://sharkattackfile.net/spreadsheets/pdf_di...
5985    http://sharkattackfile.net/spreadsheets/pdf_di...
5986    http://sharkattackfile.net/spreadsheets/pdf_di...
5987    http://sharkattackfile.net/spreadsheets/pdf_di...
5988    http://sharkattackfile.net/spreadsheets/pdf_di...
5989    http://sharkattackfile.net/spreadsheets/pdf_di...
5990    http://sharkattackfile.net/spreadsheets/pdf_di...
5991    http://sharkattackfile.net/spreadsheets/pdf_di...
Name: href formula, Length: 5992, dtype: object

In [7]:
df_cleaning["Year"].value_counts()

2015    139
2011    128
2014    125
0       124
2013    122
2008    121
2009    120
2012    117
2007    112
2006    103
2016    103
2005    103
2010    101
2000     97
1959     93
1960     93
2001     92
2004     92
2003     92
2002     88
1962     86
1961     78
1995     76
1964     66
1998     65
1999     65
1996     61
1963     61
1966     58
1997     57
       ...
1785      1
1834      1
1791      1
1733      1
1721      1
1637      1
1617      1
77        1
5         1
1703      1
1755      1
1767      1
1771      1
1779      1
1787      1
1803      1
1749      1
1807      1
1811      1
1819      1
1805      1
1831      1
1555      1
1738      1
1859      1
1742      1
1758      1
1818      1
1822      1
1595      1
Name: Year, Length: 232, dtype: int64

In [8]:
df_cleaning["Date"].value_counts()

1957                      11
1942                       9
1956                       8
1958                       7
1941                       7
1950                       7
1949                       6
No date                    6
1970s                      5
12-Apr-01                  5
1940                       5
Oct-60                     5
1959                       5
Aug-56                     5
1955                       5
05-Oct-03                  5
No date, Before 1963       5
28-Jul-95                  5
1954                       5
1945                       4
1952                       4
28-Dec-14                  4
1960                       4
Reported 10-Oct-1906       4
23-Jan-70                  4
27-Dec-08                  4
09-Jan-10                  4
14-Jun-12                  4
1890                       4
27-Jul-52                  4
                          ..
24-Mar-41                  1
10-Jan-80                  1
25-Nov-92                  1
26-Jul-01                  1
30-Jul-09                  1
13-Feb-10                  1
14-Aug-60                  1
 14-Aug-2013               1
07-Jun-08                  1
17-Apr-63                  1
22-Jan-36                  1
    16-Jan-1970            1
Before  19-Jun-1959        1
19-Jul-1847                1
13-Aug-96                  1
15-Jun-25                  1
Sep-66                     1
26-Mar-15                  1
02-Sep-1865                1
15-Dec-36                  1
24-Jun-01                  1
04-Jul-03                  1
Reported 02-April 1906     1
Reported 17-Jul-2013       1
11-Aug-02                  1
28-Jun-64                  1
Jan-91                     1
02-May-15                  1
22-Sep-98                  1
02-Sep-57                  1
Name: Date, Length: 5128, dtype: int64

Las columnas Date y Year no tienen nulos. Sin embargo, muchos registros tienen formatos diferentes y datos errÃ³neos.
Como las fechas tambiÃ©n estÃ¡n en los `case numbers`, crearemos 3 columnas nuevas: aÃ±o, mes y dÃ­a con los datos correctos.

In [9]:
'''df_clean = pd.DataFrame(columns=[])

df_fechas["Date"] = df_cleaning["Date"].copy()
display(df_fechas.head())

#df_fechas["Year"] = df_fechas["Case Number"]'''

'df_clean = pd.DataFrame(columns=[])\n\ndf_fechas["Date"] = df_cleaning["Date"].copy()\ndisplay(df_fechas.head())\n\n#df_fechas["Year"] = df_fechas["Case Number"]'

In [10]:
df_cleaning["Date"].value_counts()

1957                      11
1942                       9
1956                       8
1958                       7
1941                       7
1950                       7
1949                       6
No date                    6
1970s                      5
12-Apr-01                  5
1940                       5
Oct-60                     5
1959                       5
Aug-56                     5
1955                       5
05-Oct-03                  5
No date, Before 1963       5
28-Jul-95                  5
1954                       5
1945                       4
1952                       4
28-Dec-14                  4
1960                       4
Reported 10-Oct-1906       4
23-Jan-70                  4
27-Dec-08                  4
09-Jan-10                  4
14-Jun-12                  4
1890                       4
27-Jul-52                  4
                          ..
24-Mar-41                  1
10-Jan-80                  1
25-Nov-92                  1
26-Jul-01                  1
30-Jul-09                  1
13-Feb-10                  1
14-Aug-60                  1
 14-Aug-2013               1
07-Jun-08                  1
17-Apr-63                  1
22-Jan-36                  1
    16-Jan-1970            1
Before  19-Jun-1959        1
19-Jul-1847                1
13-Aug-96                  1
15-Jun-25                  1
Sep-66                     1
26-Mar-15                  1
02-Sep-1865                1
15-Dec-36                  1
24-Jun-01                  1
04-Jul-03                  1
Reported 02-April 1906     1
Reported 17-Jul-2013       1
11-Aug-02                  1
28-Jun-64                  1
Jan-91                     1
02-May-15                  1
22-Sep-98                  1
02-Sep-57                  1
Name: Date, Length: 5128, dtype: int64

In [11]:
'''df_clean = pd.DataFrame(columns=[])

df_fechas["Date"] = df_cleaning["Date"].copy()
display(df_fechas.head())'''

# df_fechas["Case Number"][df_fechas.str.contains('^\d\d\d\d\.\d\d\.\d\d.*')]

columna_mes = []

def findmonth(m):
    if "Jan" in m or "jan" in m:
        return 1
    elif "Feb" in m or "feb" in m:
        return 2
    elif "Mar" in m or "mar" in m:
        return 3
    elif "Apr" in m or "apr" in m:
        return 4
    elif "May" in m or "may" in m:
        return 5
    elif "Jun" in m or "jun" in m:
        return 6
    elif "Jul" in m or "jul" in m:
        return 7
    elif "Aug" in m or "aug" in m:
        return 8
    elif "Sep" in m or "sep" in m:
        return 9
    elif "Oct" in m or "oct" in m:
        return 10
    elif "Nov" in m or "nov" in m:
        return 11
    elif "Dic" in m or "dic" in m:
        return 12
    else:
        return 0


'''for e in df_fechas["Date"]:
    #year = findyear()
    month = findmonth(e)
    
    columna_mes.append(month)
    #day = findday()
'''

df_cleaning["month"] = df_cleaning["Date"].apply(findmonth)
display(df_cleaning["month"])

0       9
1       9
2       9
3       9
4       9
5       9
6       9
7       9
8       9
9       9
10      9
11      9
12      9
13      8
14      8
15      8
16      8
17      8
18      8
19      8
20      7
21      7
22      7
23      7
24      7
25      7
26      7
27      7
28      7
29      7
       ..
5962    0
5963    0
5964    0
5965    0
5966    0
5967    0
5968    0
5969    0
5970    0
5971    0
5972    0
5973    0
5974    0
5975    0
5976    0
5977    0
5978    7
5979    7
5980    7
5981    0
5982    0
5983    0
5984    0
5985    0
5986    0
5987    0
5988    0
5989    0
5990    0
5991    0
Name: month, Length: 5992, dtype: int64

In [12]:
x = df_cleaning[df_cleaning["Year"]==0]

x["Case Number"].head().value_counts()

0.0336     1
0.0493     1
0.0725     1
0.0214     1
ND-0153    1
Name: Case Number, dtype: int64

In [13]:
# TOMO LA DECISIÃ“N DE TRABAJAR

y = df_cleaning[df_cleaning["Year"]>1900]

y.head()

null_cols4 = y.isnull().sum()
print(y.shape)
null_cols4

(5311, 23)

Case Number                  0
Date                         0
Year                         0
Type                         0
Country                     22
Area                       295
Location                   363
Activity                   425
Name                       158
Sex                        504
Age                       2091
Injury                      19
Fatal (Y/N)                  9
Time                      2624
Species                   2377
Investigator or Source      13
pdf                          0
href formula                 1
href                         2
Case Number.1                0
Case Number.2                0
original order               0
month                        0
dtype: int64

In [14]:
y = df_cleaning[df_cleaning["Year"]>1905]

y.head()

null_cols4 = y.isnull().sum()
print(y.shape)
null_cols4

(5248, 23)

Case Number                  0
Date                         0
Year                         0
Type                         0
Country                     22
Area                       290
Location                   356
Activity                   421
Name                       156
Sex                        502
Age                       2044
Injury                      18
Fatal (Y/N)                  8
Time                      2570
Species                   2322
Investigator or Source      13
pdf                          0
href formula                 1
href                         2
Case Number.1                0
Case Number.2                0
original order               0
month                        0
dtype: int64

In [15]:
# TOMO LA DECISIÃ“N DE TRABAJAR CON DATOS A PARTIR DE 1900

df_cleaning = df_cleaning[df_cleaning["Year"]>1900]

null_cols4 = df_cleaning.isnull().sum()
print(df_cleaning.shape)
null_cols4

(5311, 23)

Case Number                  0
Date                         0
Year                         0
Type                         0
Country                     22
Area                       295
Location                   363
Activity                   425
Name                       158
Sex                        504
Age                       2091
Injury                      19
Fatal (Y/N)                  9
Time                      2624
Species                   2377
Investigator or Source      13
pdf                          0
href formula                 1
href                         2
Case Number.1                0
Case Number.2                0
original order               0
month                        0
dtype: int64

In [16]:

columna_mes = []
#df_cleaning.drop("month", inplace=True, axis = 0)

def findmonth(m):
    if "Jan" in m or "jan" in m:
        return 1
    elif "Feb" in m or "feb" in m:
        return 2
    elif "Mar" in m or "mar" in m:
        return 3
    elif "Apr" in m or "apr" in m or "Ap-" in m:
        return 4
    elif "May" in m or "may" in m:
        return 5
    elif "Jun" in m or "jun" in m:
        return 6
    elif "Jul" in m or "jul" in m:
        return 7
    elif "Aug" in m or "aug" in m:
        return 8
    elif "Sep" in m or "sep" in m:
        return 9
    elif "Oct" in m or "oct" in m:
        return 10
    elif "Nov" in m or "nov" in m:
        return 11
    elif "Dec" in m or "dec" in m:
        return 12
    else:
        return 0

df_cleaning["month"] = df_cleaning["Date"].apply(findmonth)
#display(df_cleaning["month"])


w = df_cleaning[df_cleaning["month"] == 0]
display(w.shape)

(285, 23)

In [17]:
df_cleaning.head()

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,...,Time,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,month
0,2016.09.18.c,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,male,M,...,13h00,NaN,"Orlando Sentinel, 9/19/2016",2016.09.18.c-NSB.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.18.c,2016.09.18.c,5993,9
1,2016.09.18.b,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,Chucky Luciano,M,...,11h00,NaN,"Orlando Sentinel, 9/19/2016",2016.09.18.b-Luciano.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.18.b,2016.09.18.b,5992,9
2,2016.09.18.a,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,male,M,...,10h43,NaN,"Orlando Sentinel, 9/19/2016",2016.09.18.a-NSB.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.18.a,2016.09.18.a,5991,9
3,2016.09.17,17-Sep-16,2016,Unprovoked,AUSTRALIA,Victoria,Thirteenth Beach,Surfing,Rory Angiolella,M,...,NaN,NaN,"The Age, 9/18/2016",2016.09.17-Angiolella.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.17,2016.09.17,5990,9
4,2016.09.15,16-Sep-16,2016,Unprovoked,AUSTRALIA,Victoria,Bells Beach,Surfing,male,M,...,NaN,2 m shark,"The Age, 9/16/2016",2016.09.16-BellsBeach.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.16,2016.09.15,5989,9

In [18]:
df_cleaning.drop(["original order"], axis = 1, inplace = True)

In [19]:
df_cleaning.head()

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,...,Fatal (Y/N),Time,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,month
0,2016.09.18.c,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,male,M,...,N,13h00,NaN,"Orlando Sentinel, 9/19/2016",2016.09.18.c-NSB.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.18.c,2016.09.18.c,9
1,2016.09.18.b,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,Chucky Luciano,M,...,N,11h00,NaN,"Orlando Sentinel, 9/19/2016",2016.09.18.b-Luciano.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.18.b,2016.09.18.b,9
2,2016.09.18.a,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,male,M,...,N,10h43,NaN,"Orlando Sentinel, 9/19/2016",2016.09.18.a-NSB.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.18.a,2016.09.18.a,9
3,2016.09.17,17-Sep-16,2016,Unprovoked,AUSTRALIA,Victoria,Thirteenth Beach,Surfing,Rory Angiolella,M,...,N,NaN,NaN,"The Age, 9/18/2016",2016.09.17-Angiolella.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.17,2016.09.17,9
4,2016.09.15,16-Sep-16,2016,Unprovoked,AUSTRALIA,Victoria,Bells Beach,Surfing,male,M,...,N,NaN,2 m shark,"The Age, 9/16/2016",2016.09.16-BellsBeach.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.16,2016.09.15,9

In [20]:
df_cleaning.drop(["Case Number.1", "Case Number.2"], axis = 1, inplace = True)

In [21]:
df_cleaning.head()

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Time,Species,Investigator or Source,pdf,href formula,href,month
0,2016.09.18.c,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,male,M,16,Minor injury to thigh,N,13h00,NaN,"Orlando Sentinel, 9/19/2016",2016.09.18.c-NSB.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,9
1,2016.09.18.b,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,Chucky Luciano,M,36,Lacerations to hands,N,11h00,NaN,"Orlando Sentinel, 9/19/2016",2016.09.18.b-Luciano.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,9
2,2016.09.18.a,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,male,M,43,Lacerations to lower leg,N,10h43,NaN,"Orlando Sentinel, 9/19/2016",2016.09.18.a-NSB.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,9
3,2016.09.17,17-Sep-16,2016,Unprovoked,AUSTRALIA,Victoria,Thirteenth Beach,Surfing,Rory Angiolella,M,NaN,Struck by fin on chest & leg,N,NaN,NaN,"The Age, 9/18/2016",2016.09.17-Angiolella.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,9
4,2016.09.15,16-Sep-16,2016,Unprovoked,AUSTRALIA,Victoria,Bells Beach,Surfing,male,M,NaN,No injury: Knocked off board by shark,N,NaN,2 m shark,"The Age, 9/16/2016",2016.09.16-BellsBeach.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,9

In [22]:
null_cols5 = df_cleaning.isnull().sum()
print(df_cleaning.shape)
null_cols5

(5311, 20)

Case Number                  0
Date                         0
Year                         0
Type                         0
Country                     22
Area                       295
Location                   363
Activity                   425
Name                       158
Sex                        504
Age                       2091
Injury                      19
Fatal (Y/N)                  9
Time                      2624
Species                   2377
Investigator or Source      13
pdf                          0
href formula                 1
href                         2
month                        0
dtype: int64

In [23]:
df_cleaning["Age"].value_counts()

17                 143
18                 139
20                 133
19                 132
16                 132
15                 127
21                 111
22                 109
24                 102
25                 100
14                  93
13                  84
23                  78
26                  77
27                  76
28                  75
29                  74
30                  72
12                  68
32                  64
35                  62
10                  51
31                  50
40                  47
38                  47
34                  45
43                  43
36                  40
33                  39
39                  36
                  ...
A.M.                 1
Elderly              1
30 & 32              1
84                   1
60s                  1
10 or 12             1
X                    1
adult                1
6Ã‚Â½                  1
Teens                1
86                   1
"young"              1
32 & 30              1
7      &    31       1
"middle-age"         1
7 or 8               1
73                   1
36 & 23              1
13 or 18             1
20?                  1
25 to 35             1
33 & 37              1
17 & 16              1
46 & 34              1
MAKE LINE GREEN      1
1                    1
17 & 35              1
23 & 26              1
30 or 36             1
Ca. 33               1
Name: Age, Length: 148, dtype: int64

In [24]:
df_cleaning['Age'].fillna(-1,inplace=True)
z = df_cleaning[df_cleaning["Age"].str.contains("&")==True]
print(z.shape)
display(z)

(22, 20)

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Time,Species,Investigator or Source,pdf,href formula,href,month
475,2013.03.10.a,10-Mar-13,2013,Unprovoked,PHILIPPINES,Palawan,Off Likas Island,Swimming to shore with floatioon devices after...,Alvin Lovido & John Paul Mangaoang,M,28 & 26,Minor leg injuries,N,NaN,"""small sharks""","E. Badilla, InterAksyon.com, 3/15/2013",2013.03.10.a-PhilippineMarines.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,3
1282,2006.01.28.R,Reported 28-Jan-2006,2006,Boat,ATLANTIC OCEAN,300 miles from Antigua,NaN,Competing in the Woodvale Atlantic Rowing Race,"Mayabrit, an ocean rowing boat. Occupants: And...",M,46 & 34,No injury to occupants; shark rammed boat repe...,N,NaN,12' shark,"N. Bevan, icwales.icnetwork.co.uk, 1/28/2006",2006.01.28.R-Mayabrit.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1
1284,2006.01.23,23-Jan-06,2006,Boat,ATLANTIC OCEAN,800 miles from land,NaN,Competing in the Woodvale Atlantic Rowing Race,"Rowgirls, an ocean rowing boat. Occupants: Sal...",F,"28, 23 & 30","No injury to occupants; a shark, accidentally ...",N,NaN,NaN,"Northants News, 1/25/2006",2006.01.23-Rowgirls.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1
1519,2003.09.14.b,14-Sep-03,2003,Boat,SOUTH AFRICA,Western Cape Province,Melkbosstrand,Fishing,"inflatable boat, occupants: Rudolf Bokelmann a...",NaN,36 & 26,"No injury to occupants, shark bit boat",N,09h40,2 m cow shark,"E. Ritter, GSAF",2003.09.14.b-CowShark.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,9
1701,2001.08.12,12-Aug-01,2001,Unprovoked,THAILAND,Rayong Province,Laem Mae Pim Beach,Fell off banana boat,O. Jaimaung & friend,M,21 & ?,Legs bitten,N,NaN,3 m [10'] shark,O. Jaimuang,2001.08.12-Jaimuang.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,8
1802,2000.08.10,10-Aug-00,2000,Invalid,USA,Florida,Florida Keys,Attempting to illegally enter the USA,Juan & Alex Bueno,M,23 & 20,Shark involvement probably post-mortem,Y,NaN,NaN,Press clippings,2000.08.10-BuenoBrothers.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,8
2197,1994.09.11.R,Reported 11-Sep-1994,1994,Sea Disaster,USA,Florida,Florida Straits,Adrift on refugee raft,2 Cuban brothers,M,7 & 31,FATAL,Y,NaN,NaN,"Sunday Herald Sun, 9/11/1994, p.25",1994.09.11.R-CubanRefugees.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,9
2286,1993.01.04,04-Jan-93,1993,Boat,CARIBBEAN SEA,NaN,Off Dominican Republic,,"canoe, occupants: Chris Newman & Stewart Newman",M,32 & 30,"No injury to occupants. Sharks, attracted to o...",N,NaN,Two 3 m [10'] oceanic whitetip sharks,"A. MacCormick, p.100",1993.01.04-DominicanRepublic.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1
3233,1968.08.24,24-Aug-68,1968,Unprovoked,USA,Florida,Half mile north of Juno Beach Pier,Playing with a frisbee in the shallows,Colleen Chamberlin & Scott Chamberlin,NaN,9 & 12,"Shark bumped Colleen, the nudged Scott, then b...",N,16h00,a small hammerhead shark,"M. Vorenberg, GSAF",1968.08.24-Chamberlin.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,8
3291,1967.08.10,10-Aug-67,1967,Invalid,AUSTRALIA,New South Wales,Jervis Bay,Anti-sabotage night dive exercise alongside de...,"J.T. Hales and Kenneth J. Hislop, Australian N...",M,? & 19,"Disappeared, no trace of men or equipment, sha...",Y,Night,NaN,"H.D. Baldridge, p.184",1967.08.10-Hales-Hislop.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,8
3516,1963.08.00,Aug-63,1963,Unprovoked,DOMINICAN REPUBLIC,Santo Domingo,Rio Haina Port,"Swimming, when caught in heavy seas",2 males,M,23 & 26,"FATAL. Eyewitness said, ""One was thrown in the...",Y,NaN,8 sharks,"A. Gigante, Jr; H.D. Baldridge; M. McDiarmid, ...",1963.08.00-2males.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,8
3654,1961.09.02.R,Reported 06-Sep-1961,1961,Provoked,ITALY,Venice Province,Chioggia,Fishing,Pollione Perrini & Fioravante Perini,M,33 & 37,Left foot & right hand bitten by netted shark ...,N,NaN,1 m shark,"C. Moore, GSAF",1961.09.06.R-Chioggia.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,9
3760,1960.06.07,07-Jun-60,1960,Invalid,USA,California,"10 miles off Santa Barbara, Santa Barbara County",Testing classified underwater electronic gear ...,"Paul Timothy Lovette, Dr. Neal Beardsley, Jame...",M,"37, 67, 35, 27, ? & 27","Legs & arms bitten, coroner unable to determin...",N,NaN,NaN,"L.A. Times, 6/10/1960; L. Schultz & M. Malin, ...",1960.06.07-Raytheon.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,6
3772,1960.04.14,14-Apr-60,1960,Invalid,BERMUDA,"33N, 68W",Royal Canadian Navy CS2F-1 aircraft ditched in...,Floating on a raft,"Crew of aircraft: McGreevy, Beakley, Rosenthal...",M,"21, 34,24 & 35","No injury, shark bumped raft",N,09h00 - 09h30,Five 1.8 m [6'] sharks,"G.S. Beakley, RCN; L. Schultz & M. Malin, p.55...",1960.04.14-Beakley-recheck text-March.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,4
3783,1960.02.29,29-Feb-60,1960,Unprovoked,AUSTRALIA,Tasmania,Ralph Bay,"Wading, fishing for flounder",Malcolm Robertson & Tom Hasler,M,30 & 32,"No injury, Robertson knocked over & Hasler bru...",N,Night,Two 2.1 m [7'] sharks,Hobart Mercury 3/3/1960,1960.02.29-Robertson-Hasler.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2
3809,1959.12.28,28-Dec-59,1959,Boat,AUSTRALIA,New South Wales,"Leichardt, Sydney",Fishing,"plywood dinghy, occupants: Jack Deegan & Trevo...",NaN,50 & 30,No injury to occupants,N,Late night,2.4 m [8'] shark,"Daily Mirror (Sydney), 12/29/1959",1959.12.28-NV-Deegan-dinghy.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,12
3813,1959.12.11,11-Dec-59,1959,Provoked,AUSTRALIA,Victoria,"Altona, Melbourne","Spearfishing, Smith & Walker touched shark wi...",Barry Smith & Harold Walker,M,17 & 35,"Smith hit by tail of shark, Walker sustained c...",N,NaN,2.7 m [9'] shark,"V.M. Coppleson (1962), p.252;",1959.12.11-Smith-Walker.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,12
3852,1959.08.02,21764,1959,Invalid,ITALY,Tuscany,"Cala del Corvo, Isola del Giglio",Scuba diving,Karl Pollerer & Eric Eisesenid,M,34 & 19,Probable drowing. Shark involvement unconfirmed,Y,NaN,NaN,"C. Moore, GSAF",1959.08.02-Giglio.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,0
3892,1959.01.02,02-Jan-59,1959,Unprovoked,MOZAMBIQUE,Maputo Province,Off Inhaca Island,Swimming ashore from fishing boat swamped and ...,Eric Suttie & Peter Murray,M,33 & 26,"Suttie's lower abdomen was bitten, Murray disa...",Y,08h00,NaN,"M. Levine, GSAF; Cape Argus 1/3/1959; Natal Me...",1959.01.02-Suttie.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1
4360,1947.01.14,14-Jan-47,1947,Boating,AUSTRALIA,New South Wales,"Berry's Bay, Sydney Harbour",Rowing,"rowboat, occupants: Bob Scott & John Blackwell",NaN,17 & 16,"No injury, shark lifted the boat 0.5 m out of ...",N,NaN,"4.5 m [14'9""] shark","A. Sharpe, p.73",1947.01.14-rowboat.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1
4769,1932.01.06,06-Jan-32,1932,Provoked,MEXICO,Baja California,Descano Point,Fishing,Efrain Ybarra & Francisco Durazzo,M,36 & 23,Hooked shark capsized rowboat & the 2 men were...,Y,NaN,NaN,"NY Herald Tribune, 1/8/1933",1932.01.06-BajaFishermen.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1
4950,1924.07.04,04-Jul-24,1924,Boating,USA,California,"Newport Beach, Orange County",Fishing,"18' boat, occupants Richard Gunther & Donald C...",M,? & 14,"No injury, shark tore hole in the side of the ...",N,NaN,NaN,"The Daily Pilot, 3/6/2010, citing The Times 7/...",1924.07.04-boat-NewportBeach.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,7

In [25]:
# BORRO LOS ATAQUES DE TYPE INVALID, POR QUE NO SON ATAQUES REALES
df_cleaning=df_cleaning[df_cleaning["Type"] != "Invalid"]

In [26]:
df_cleaning.shape

(4862, 20)

In [27]:
df_cleaning['Age'].fillna(-1,inplace=True)
z = df_cleaning[(df_cleaning["Age"].str.contains("&")==True) | (df_cleaning["Age"].str.contains("and")==True)]
print(z.shape)
display(z)

(17, 20)

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Time,Species,Investigator or Source,pdf,href formula,href,month
475,2013.03.10.a,10-Mar-13,2013,Unprovoked,PHILIPPINES,Palawan,Off Likas Island,Swimming to shore with floatioon devices after...,Alvin Lovido & John Paul Mangaoang,M,28 & 26,Minor leg injuries,N,NaN,"""small sharks""","E. Badilla, InterAksyon.com, 3/15/2013",2013.03.10.a-PhilippineMarines.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,3
1282,2006.01.28.R,Reported 28-Jan-2006,2006,Boat,ATLANTIC OCEAN,300 miles from Antigua,NaN,Competing in the Woodvale Atlantic Rowing Race,"Mayabrit, an ocean rowing boat. Occupants: And...",M,46 & 34,No injury to occupants; shark rammed boat repe...,N,NaN,12' shark,"N. Bevan, icwales.icnetwork.co.uk, 1/28/2006",2006.01.28.R-Mayabrit.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1
1284,2006.01.23,23-Jan-06,2006,Boat,ATLANTIC OCEAN,800 miles from land,NaN,Competing in the Woodvale Atlantic Rowing Race,"Rowgirls, an ocean rowing boat. Occupants: Sal...",F,"28, 23 & 30","No injury to occupants; a shark, accidentally ...",N,NaN,NaN,"Northants News, 1/25/2006",2006.01.23-Rowgirls.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1
1519,2003.09.14.b,14-Sep-03,2003,Boat,SOUTH AFRICA,Western Cape Province,Melkbosstrand,Fishing,"inflatable boat, occupants: Rudolf Bokelmann a...",NaN,36 & 26,"No injury to occupants, shark bit boat",N,09h40,2 m cow shark,"E. Ritter, GSAF",2003.09.14.b-CowShark.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,9
1701,2001.08.12,12-Aug-01,2001,Unprovoked,THAILAND,Rayong Province,Laem Mae Pim Beach,Fell off banana boat,O. Jaimaung & friend,M,21 & ?,Legs bitten,N,NaN,3 m [10'] shark,O. Jaimuang,2001.08.12-Jaimuang.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,8
2197,1994.09.11.R,Reported 11-Sep-1994,1994,Sea Disaster,USA,Florida,Florida Straits,Adrift on refugee raft,2 Cuban brothers,M,7 & 31,FATAL,Y,NaN,NaN,"Sunday Herald Sun, 9/11/1994, p.25",1994.09.11.R-CubanRefugees.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,9
2286,1993.01.04,04-Jan-93,1993,Boat,CARIBBEAN SEA,NaN,Off Dominican Republic,,"canoe, occupants: Chris Newman & Stewart Newman",M,32 & 30,"No injury to occupants. Sharks, attracted to o...",N,NaN,Two 3 m [10'] oceanic whitetip sharks,"A. MacCormick, p.100",1993.01.04-DominicanRepublic.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1
3233,1968.08.24,24-Aug-68,1968,Unprovoked,USA,Florida,Half mile north of Juno Beach Pier,Playing with a frisbee in the shallows,Colleen Chamberlin & Scott Chamberlin,NaN,9 & 12,"Shark bumped Colleen, the nudged Scott, then b...",N,16h00,a small hammerhead shark,"M. Vorenberg, GSAF",1968.08.24-Chamberlin.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,8
3516,1963.08.00,Aug-63,1963,Unprovoked,DOMINICAN REPUBLIC,Santo Domingo,Rio Haina Port,"Swimming, when caught in heavy seas",2 males,M,23 & 26,"FATAL. Eyewitness said, ""One was thrown in the...",Y,NaN,8 sharks,"A. Gigante, Jr; H.D. Baldridge; M. McDiarmid, ...",1963.08.00-2males.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,8
3654,1961.09.02.R,Reported 06-Sep-1961,1961,Provoked,ITALY,Venice Province,Chioggia,Fishing,Pollione Perrini & Fioravante Perini,M,33 & 37,Left foot & right hand bitten by netted shark ...,N,NaN,1 m shark,"C. Moore, GSAF",1961.09.06.R-Chioggia.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,9
3783,1960.02.29,29-Feb-60,1960,Unprovoked,AUSTRALIA,Tasmania,Ralph Bay,"Wading, fishing for flounder",Malcolm Robertson & Tom Hasler,M,30 & 32,"No injury, Robertson knocked over & Hasler bru...",N,Night,Two 2.1 m [7'] sharks,Hobart Mercury 3/3/1960,1960.02.29-Robertson-Hasler.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2
3809,1959.12.28,28-Dec-59,1959,Boat,AUSTRALIA,New South Wales,"Leichardt, Sydney",Fishing,"plywood dinghy, occupants: Jack Deegan & Trevo...",NaN,50 & 30,No injury to occupants,N,Late night,2.4 m [8'] shark,"Daily Mirror (Sydney), 12/29/1959",1959.12.28-NV-Deegan-dinghy.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,12
3813,1959.12.11,11-Dec-59,1959,Provoked,AUSTRALIA,Victoria,"Altona, Melbourne","Spearfishing, Smith & Walker touched shark wi...",Barry Smith & Harold Walker,M,17 & 35,"Smith hit by tail of shark, Walker sustained c...",N,NaN,2.7 m [9'] shark,"V.M. Coppleson (1962), p.252;",1959.12.11-Smith-Walker.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,12
3892,1959.01.02,02-Jan-59,1959,Unprovoked,MOZAMBIQUE,Maputo Province,Off Inhaca Island,Swimming ashore from fishing boat swamped and ...,Eric Suttie & Peter Murray,M,33 & 26,"Suttie's lower abdomen was bitten, Murray disa...",Y,08h00,NaN,"M. Levine, GSAF; Cape Argus 1/3/1959; Natal Me...",1959.01.02-Suttie.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1
4360,1947.01.14,14-Jan-47,1947,Boating,AUSTRALIA,New South Wales,"Berry's Bay, Sydney Harbour",Rowing,"rowboat, occupants: Bob Scott & John Blackwell",NaN,17 & 16,"No injury, shark lifted the boat 0.5 m out of ...",N,NaN,"4.5 m [14'9""] shark","A. Sharpe, p.73",1947.01.14-rowboat.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1
4769,1932.01.06,06-Jan-32,1932,Provoked,MEXICO,Baja California,Descano Point,Fishing,Efrain Ybarra & Francisco Durazzo,M,36 & 23,Hooked shark capsized rowboat & the 2 men were...,Y,NaN,NaN,"NY Herald Tribune, 1/8/1933",1932.01.06-BajaFishermen.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1
4950,1924.07.04,04-Jul-24,1924,Boating,USA,California,"Newport Beach, Orange County",Fishing,"18' boat, occupants Richard Gunther & Donald C...",M,? & 14,"No injury, shark tore hole in the side of the ...",N,NaN,NaN,"The Daily Pilot, 3/6/2010, citing The Times 7/...",1924.07.04-boat-NewportBeach.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,7

In [28]:
df_cleaning["Sex "].value_counts()

M      3919
F       495
M         2
lli       1
.         1
N         1
Name: Sex , dtype: int64

In [29]:
df_cleaning.rename(index=str, columns={"Sex ": "Sex", "month": "Month", "Species ": "Species"}, inplace = True)

In [30]:
df_cleaning["Species"].value_counts()

White shark                                                                        149
Tiger shark                                                                         58
Bull shark                                                                          45
4' shark                                                                            39
6' shark                                                                            37
1.8 m [6'] shark                                                                    33
1.5 m [5'] shark                                                                    31
1.2 m [4'] shark                                                                    26
3' shark                                                                            24
5' shark                                                                            23
4' to 5' shark                                                                      22
3 m [10'] shark                                                                     20
2 m shark                                                                           20
Wobbegong shark                                                                     20
3' to 4' shark                                                                      18
3 m shark                                                                           16
2.4 m [8'] shark                                                                    16
Blue shark                                                                          14
Blacktip shark                                                                      14
1.2 m to 1.5 m [4' to 5'] shark                                                     14
3.7 m [12'] shark                                                                   14
"a small shark"                                                                     13
Mako shark                                                                          13
6 m [20'] white shark                                                               12
Raggedtooth shark                                                                   12
Bronze whaler shark                                                                 12
5 m [16.5'] white shark                                                             12
1.5 m shark                                                                         12
Nurse shark                                                                         11
Zambesi shark                                                                       11
                                                                                  ...
18' shark                                                                            1
Nurse shark, 60 cm to 90 cm [2' to 3']                                               1
Mako shark, 1.8 m [6']                                                               1
Wobbegong shark, 4'                                                                  1
Grey nurse shark, 2 m                                                                1
2.7 m [9'] shark with black-tipped pectoral fins                                     1
Lemon shark, 4' to 5'                                                                1
Bull shark, 4 m [13']                                                                1
Tiger shark 3 m  [10']                                                               1
3.7 m [12'] shark & may have been another shark nearby                               1
3m shark                                                                             1
12' to 18' shark                                                                     1
60 cm  shark                                                                         1
3 m hammerhead shark                                                                 1
Raggedtooth shark, 2 m [6.75']                                                       1
Possibly a 1.5 m [5'] blacktip or spinner shark                                      1
Blacktip shark, 1.8 m [6']                                                           1
4' shark?                                                                            1
Grey nurse shark, 1.5 m [5']                                                         1
Reported to involve a white shark                                                    1
1.8 m [6'] blacktip shark or Caribbean reef shark                                    1
"Blue nose sharks"                                                                   1
Reported to involve a hammerhead shark                                               1
White shark (tooth fragments recovered from hull of boat)                            1
Hammerhead shark, 1.8 m [6'] S. zygena identified by C. Limbaugh on description      1
Hammerhead shark?+O2356                                                              1
Raggedtooth shark, 2 m [6'9"]                                                        1
Zambesi shark, 1.2 m [4']                                                            1
White shark, 4 m white shark                                                         1
2.7 m [9']shark                                                                      1
Name: Species, Length: 1407, dtype: int64

In [31]:
df_cleaning.columns

Index(['Case Number', 'Date', 'Year', 'Type', 'Country', 'Area', 'Location',
       'Activity', 'Name', 'Sex', 'Age', 'Injury', 'Fatal (Y/N)', 'Time',
       'Species', 'Investigator or Source', 'pdf', 'href formula', 'href',
       'Month'],
      dtype='object')

In [32]:
#df_ages = pd.DataFrame(columns=df_cleaning.columns)
#display(df_ages)

In [33]:
df_ages = pd.DataFrame(columns=df_cleaning.columns)

import re
import math

for e in z["Age"]:
    ages = re.findall(r"[\d]+", e)
    for q in ages:
        df_ages = pd.concat([df_ages, z[z["Age"]==e]], ignore_index = True)
        df_ages["Age"][df_ages.index.max()] = q

display(df_ages)

/usr/lib/python3/dist-packages/ipykernel_launcher.py:9: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  if __name__ == '__main__':
/usr/lib/python3/dist-packages/ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  # Remove the CWD from sys.path while we load stuff.

,Activity,Age,Area,Case Number,Country,Date,Fatal (Y/N),Injury,Investigator or Source,Location,...,Sex,Species,Species,Time,Type,Year,href,href formula,month,pdf
0,Swimming to shore with floatioon devices after...,28,Palawan,2013.03.10.a,PHILIPPINES,10-Mar-13,N,Minor leg injuries,"E. Badilla, InterAksyon.com, 3/15/2013",Off Likas Island,...,M,NaN,"""small sharks""",NaN,Unprovoked,2013,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,3.0,2013.03.10.a-PhilippineMarines.pdf
1,Swimming to shore with floatioon devices after...,26,Palawan,2013.03.10.a,PHILIPPINES,10-Mar-13,N,Minor leg injuries,"E. Badilla, InterAksyon.com, 3/15/2013",Off Likas Island,...,M,NaN,"""small sharks""",NaN,Unprovoked,2013,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,3.0,2013.03.10.a-PhilippineMarines.pdf
2,Competing in the Woodvale Atlantic Rowing Race,46,300 miles from Antigua,2006.01.28.R,ATLANTIC OCEAN,Reported 28-Jan-2006,N,No injury to occupants; shark rammed boat repe...,"N. Bevan, icwales.icnetwork.co.uk, 1/28/2006",NaN,...,M,NaN,12' shark,NaN,Boat,2006,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1.0,2006.01.28.R-Mayabrit.pdf
3,Competing in the Woodvale Atlantic Rowing Race,34,300 miles from Antigua,2006.01.28.R,ATLANTIC OCEAN,Reported 28-Jan-2006,N,No injury to occupants; shark rammed boat repe...,"N. Bevan, icwales.icnetwork.co.uk, 1/28/2006",NaN,...,M,NaN,12' shark,NaN,Boat,2006,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1.0,2006.01.28.R-Mayabrit.pdf
4,Competing in the Woodvale Atlantic Rowing Race,28,800 miles from land,2006.01.23,ATLANTIC OCEAN,23-Jan-06,N,"No injury to occupants; a shark, accidentally ...","Northants News, 1/25/2006",NaN,...,F,NaN,NaN,NaN,Boat,2006,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1.0,2006.01.23-Rowgirls.pdf
5,Competing in the Woodvale Atlantic Rowing Race,23,800 miles from land,2006.01.23,ATLANTIC OCEAN,23-Jan-06,N,"No injury to occupants; a shark, accidentally ...","Northants News, 1/25/2006",NaN,...,F,NaN,NaN,NaN,Boat,2006,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1.0,2006.01.23-Rowgirls.pdf
6,Competing in the Woodvale Atlantic Rowing Race,30,800 miles from land,2006.01.23,ATLANTIC OCEAN,23-Jan-06,N,"No injury to occupants; a shark, accidentally ...","Northants News, 1/25/2006",NaN,...,F,NaN,NaN,NaN,Boat,2006,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1.0,2006.01.23-Rowgirls.pdf
7,Fishing,36,Western Cape Province,2003.09.14.b,SOUTH AFRICA,14-Sep-03,N,"No injury to occupants, shark bit boat","E. Ritter, GSAF",Melkbosstrand,...,NaN,NaN,2 m cow shark,09h40,Boat,2003,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,9.0,2003.09.14.b-CowShark.pdf
8,Fishing,26,Western Cape Province,2003.09.14.b,SOUTH AFRICA,14-Sep-03,N,"No injury to occupants, shark bit boat","E. Ritter, GSAF",Melkbosstrand,...,NaN,NaN,2 m cow shark,09h40,Boat,2003,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,9.0,2003.09.14.b-CowShark.pdf
9,Fell off banana boat,21,Rayong Province,2001.08.12,THAILAND,12-Aug-01,N,Legs bitten,O. Jaimuang,Laem Mae Pim Beach,...,M,NaN,3 m [10'] shark,NaN,Unprovoked,2001,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,8.0,2001.08.12-Jaimuang.pdf
10,Adrift on refugee raft,7,Florida,1994.09.11.R,USA,Reported 11-Sep-1994,Y,FATAL,"Sunday Herald Sun, 9/11/1994, p.25",Florida Straits,...,M,NaN,NaN,NaN,Sea Disaster,1994,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,9.0,1994.09.11.R-CubanRefugees.pdf
11,Adrift on refugee raft,31,Florida,1994.09.11.R,USA,Reported 11-Sep-1994,Y,FATAL,"Sunday Herald Sun, 9/11/1994, p.25",Florida Straits,...,M,NaN,NaN,NaN,Sea Disaster,1994,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,9.0,1994.09.11.R-CubanRefugees.pdf
12,,32,NaN,1993.01.04,CARIBBEAN SEA,04-Jan-93,N,"No injury to occupants. Sharks, attracted to o...","A. MacCormick, p.100",Off Dominican Republic,...,M,NaN,Two 3 m [10'] oceanic whitetip sharks,NaN,Boat,1993,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1.0,1993.01.04-DominicanRepublic.pdf
13,,30,NaN,1993.01.04,CARIBBEAN SEA,04-Jan-93,N,"No injury to occupants. Sharks, attracted to o...","A. MacCormick, p.100",Off Dominican Republic,...,M,NaN,Two 3 m [10'] oceanic whitetip sharks,NaN,Boat,1993,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1.0,1993.01.04-DominicanRepublic.pdf
14,Playing with a frisbee in the shallows,9,Florida,1968.08.24,USA,24-Aug-68,N,"Shark bumped Colleen, the nudged Scott, then b...","M. Vorenberg, GSAF",Half mile north of Juno Beach Pier,...,NaN,NaN,a small hammerhead shark,16h00,Unprovoked,1968,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,8.0,1968.08.24-Chamberlin.pdf
15,Playing with a frisbee in the shallows,12,Florida,1968.08.24,USA,24-Aug-68,N,"Shark bumped Colleen, the nudged Scott, then b...","M. Vorenberg, GSAF",Half mile north of Juno Beach Pier,...,NaN,NaN,a small hammerhead shark,16h00,Unprovoked,1968,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,8.0,1968.08.24-Chamberlin.pdf
16,"Swimming, when caught in heavy seas",23,Santo Domingo,1963.08.00,DOMINICAN REPUBLIC,Aug-63,Y,"FATAL. Eyewitness said, ""One was thrown in the...","A. Gigante, Jr; H.D. Baldridge; M. McDiarmid, ...",Rio Haina Port,...,M,NaN,8 sharks,NaN,Unprovoked,1963,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,8.0,1963.08.00-2males.pdf
17,"Swimming, when caught in heavy seas",26,Santo Domingo,1963.08.00,DOMINICAN REPUBLIC,Aug-63,Y,"FATAL. Eyewitness said, ""One was thrown in the...","A. Gigante, Jr; H.D. Baldridge; M. McDiarmid, ...",Rio Haina Port,...,M,NaN,8 sharks,NaN,Unprovoked,1963,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,8.0,1963.08.00-2males.pdf
18,Fishing,33,Venice Province,1961.09.02.R,ITALY,Reported 06-Sep-1961,N,Left foot & right hand bitten by netted shark ...,"C. Moore, GSAF",Chioggia,...,M,NaN,1 m shark,NaN,Provoked,1961,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,9.0,1961.09.06.R-Chioggia.pdf
19,Fishing,37,Venice Province,1961.09.02.R,ITALY,Reported 06-Sep-1961,N,Left foot & right hand bitten by netted shark ...,"C. Moore, GSAF",Chioggia,...,M,NaN,1 m shark,NaN,Provoked,1961,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,9.0,1961.09.06.R-Chioggia.pdf
20,"Wading, fishing for flounder",30,Tasmania,1960.02.29,AUSTRALIA,29-Feb-60,N,"No injury, Robertson knocked over & Hasler bru...",Hobart Mercury 3/3/1960,Ralph Bay,...,M,NaN,Two 2.1 m [7'] sharks,Night,Unprovoked,1960,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2.0,1960.02.29-Robertson-Hasler.pdf
21,"Wading, fishing for flounder",32,Tasmania,1960.02.29,AUSTRALIA,29-Feb-60,N,"No injury, Robertson knocked over & Hasler bru...",Hobart Mercury 3/3/1960,Ralph Bay,...,M,NaN,Two 2.1 m [7'] sharks,Night,Unprovoked,1960,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2.0,1960.02.29-Robertson-Hasler.pdf
22,Fishing,50,New South Wales,1959.12.28,AUSTRALIA,28-Dec-59,N,No injury to occupants,"Daily Mirror (Sydney), 12/29/1959","Leichardt, Sydney",...,NaN,NaN,2.4 m [8'] shark,Late night,Boat,1959,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,12.0,1959.12.28-NV-Deegan-dinghy.pdf
23,Fishing,30,New South Wales,1959.12.28,AUSTRALIA,28-Dec-59,N,No injury to occupants,"Daily Mirror (Sydney), 12/29/1959","Leichardt, Sydney",...,NaN,NaN,2.4 m [8'] shark,Late night,Boat,1959,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,12.0,1959.12.28-NV-Deegan-dinghy.pdf
24,"Spearfishing, Smith & Walker touched shark wi...",17,Victoria,1959.12.11,AUSTRALIA,11-Dec-59,N,"Smith hit by tail of shark, Walker sustained c...","V.M. Coppleson (1962), p.252;","Altona, Melbourne",...,M,NaN,2.7 m [9'] shark,NaN,Provoked,1959,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,12.0,1959.12.11-Smith-Walker.pdf
25,"Spearfishing, Smith & Walker touched shark wi...",35,Victoria,1959.12.11,AUSTRALIA,11-Dec-59,N,"Smith hit by tail of shark, Walker sustained c...","V.M. Coppleson (1962), p.252;","Altona, Melbourne",...,M,NaN,2.7 m [9'] shark,NaN,Provoked,1959,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,12.0,1959.12.11-Smith-Walker.pdf
26,Swimming ashore from fishing boat swamped and ...,33,Maputo Province,1959.01.02,MOZAMBIQUE,02-Jan-59,Y,"Suttie's lower abdomen was bitten, Murray disa...","M. Levine, GSAF; Cape Argus 1/3/1959; Natal Me...",Off Inhaca Island,...,M,NaN,NaN,08h00,Unprovoked,1959,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1.0,1959.01.02-Suttie.pdf
27,Swimming ashore from fishing boat swamped and ...,26,Maputo Province,1959.01.02,MOZAMBIQUE,02-Jan-59,Y,"Suttie's lower abdomen was bitten, Murray disa...","M. Levine, GSAF; Cape Argus 1/3/1959; Natal Me...",Off Inhaca Island,...,M,NaN,NaN,08h00,Unprovoked,1959,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1.0,1959.01.02-Suttie.pdf
28,Rowing,17,New South Wales,1947.01.14,AUSTRALIA,14-Jan-47,N,"No injury, shark lifted the boat 0.5 m out of ...","A. Sharpe, p.73","Berry's Bay, Sydney Harbour",...,NaN,NaN,"4.5 m [14'9""] shark",NaN,Boating,1947,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1.0,1947.01.14-rowboat.pdf
29,Rowing,16,New South Wales,1947.01.14,AUSTRALIA,14-Jan-47,N,"No injury, shark lifted the boat 0.5 m out of ...","A. Sharpe, p.73","Berry's Bay, Sydney Harbour",...,NaN,NaN,"4.5 m [14'9""] shark",NaN,Boating,1947,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1.0,1947.01.14-rowboat.pdf
30,Fishing,36,Baja California,1932.01.06,MEXICO,06-Jan-32,Y,Hooked shark capsized rowboat & the 2 men were...,"NY Herald Tribune, 1/8/1933",Descano Point,...,M,NaN,NaN,NaN,Provoked,1932,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1.0,1932.01.06-BajaFishermen.pdf
31,Fishing,23,Baja California,1932.01.06,MEXICO,06-Jan-32,Y,Hooked shark capsized rowboat & the 2 men were...,"NY Herald Tribune, 1/8/1933",Descano Point,...,M,NaN,NaN,NaN,Provoked,1932,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1.0,1932.01.06-BajaFishermen.pdf
32,Fishing,14,California,1924.07.04,USA,04-Jul-24,N,"No injury, shark tore hole in the side of the ...","The Daily Pilot, 3/6/2010, citing The Times 7/...","Newport Beach, Orange County",...,M,NaN,NaN,NaN,Boating,1924,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,7.0,1924.07.04-boat-NewportBeach.pdf

In [48]:
df_cleaning = df_cleaning[(df_cleaning["Age"].str.contains("&")!=True)]
print(df_cleaning.shape)
#df_cleaning = pd.concat([df_cleaning, df_ages], ignore_index = True)
print(df_cleaning.shape)

(4877, 23)
(4877, 23)

In [35]:
display(df_cleaning.head())

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Time,Species,Investigator or Source,pdf,href formula,href,Month
0,2016.09.18.c,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,male,M,16,Minor injury to thigh,N,13h00,NaN,"Orlando Sentinel, 9/19/2016",2016.09.18.c-NSB.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,9
1,2016.09.18.b,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,Chucky Luciano,M,36,Lacerations to hands,N,11h00,NaN,"Orlando Sentinel, 9/19/2016",2016.09.18.b-Luciano.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,9
2,2016.09.18.a,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,male,M,43,Lacerations to lower leg,N,10h43,NaN,"Orlando Sentinel, 9/19/2016",2016.09.18.a-NSB.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,9
3,2016.09.17,17-Sep-16,2016,Unprovoked,AUSTRALIA,Victoria,Thirteenth Beach,Surfing,Rory Angiolella,M,-1,Struck by fin on chest & leg,N,NaN,NaN,"The Age, 9/18/2016",2016.09.17-Angiolella.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,9
4,2016.09.15,16-Sep-16,2016,Unprovoked,AUSTRALIA,Victoria,Bells Beach,Surfing,male,M,-1,No injury: Knocked off board by shark,N,NaN,2 m shark,"The Age, 9/16/2016",2016.09.16-BellsBeach.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,9

In [36]:
null_cols = df_cleaning.isnull().sum()
print(null_cols)

Case Number                  0
Date                         0
Year                         0
Type                         0
Country                     18
Area                       262
Location                   321
Activity                   327
Name                       115
Sex                        439
Age                          0
Injury                      13
Fatal (Y/N)                  4
Time                      2302
Species                   2155
Investigator or Source      11
pdf                          0
href formula                 1
href                         1
Month                        0
dtype: int64

In [37]:
df_cleaning["Sex"].value_counts()

M      3907
F       494
M         2
lli       1
.         1
N         1
Name: Sex, dtype: int64

In [38]:
df_cleaning[df_cleaning["Sex"]=="N"]

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Time,Species,Investigator or Source,pdf,href formula,href,Month
4708,1934.07.11,11-Jul-34,1934,Boating,AUSTRALIA,New South Wales,Cronulla,Fishing,"18' boat, occupants William & Leslie Newton",N,-1,No injury to occupants Sharks continually foll...,N,NaN,"Blue pointer, 11'","G.P. Whitley, ref: Daily Telegraph, 7/11/1934 ...",1934.07.11-Newton-boat-Australia.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,7

In [39]:
df_sex = pd.DataFrame(columns=df_cleaning.columns)

df_sex = pd.concat([df_sex, df_cleaning[df_cleaning["Sex"]=="N"]], ignore_index = True)
df_sex = pd.concat([df_sex, df_cleaning[df_cleaning["Sex"]=="N"]], ignore_index = True)

df_sex["Sex"][0] = "M"
df_sex["Sex"][1] = "F"
display(df_sex)

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Time,Species,Investigator or Source,pdf,href formula,href,Month
0,1934.07.11,11-Jul-34,1934,Boating,AUSTRALIA,New South Wales,Cronulla,Fishing,"18' boat, occupants William & Leslie Newton",M,-1,No injury to occupants Sharks continually foll...,N,NaN,"Blue pointer, 11'","G.P. Whitley, ref: Daily Telegraph, 7/11/1934 ...",1934.07.11-Newton-boat-Australia.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,7
1,1934.07.11,11-Jul-34,1934,Boating,AUSTRALIA,New South Wales,Cronulla,Fishing,"18' boat, occupants William & Leslie Newton",F,-1,No injury to occupants Sharks continually foll...,N,NaN,"Blue pointer, 11'","G.P. Whitley, ref: Daily Telegraph, 7/11/1934 ...",1934.07.11-Newton-boat-Australia.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,7

In [49]:
print(df_cleaning.shape)
df_cleaning = df_cleaning[df_cleaning["Sex"]!="N"]
print(df_cleaning.shape)
#df_cleaning = pd.concat([df_cleaning, df_sex], ignore_index = True)
print(df_cleaning.shape)

(4877, 23)
(4877, 23)
(4879, 23)

/usr/lib/python3/dist-packages/ipykernel_launcher.py:4: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  after removing the cwd from sys.path.

In [41]:
df_cleaning["Sex"][df_cleaning["Sex"]=="lli"]="M"

In [42]:
df_cleaning[df_cleaning["Sex"]=="lli"]

Empty DataFrame
Columns: [Case Number, Date, Year, Type, Country, Area, Location, Activity, Name, Sex, Age, Injury, Fatal (Y/N), Time, Species, Investigator or Source, pdf, href formula, href, Month]
Index: []

In [45]:
df_cleaning[df_cleaning["Sex"]=="."]

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Time,Species,Investigator or Source,pdf,href formula,href,Month
5201,1908.06.02.R,Reported 02-Jun-1908,1908,Sea Disaster,PAPUA NEW GUINEA,New Britain,Matupi,.,NaN,.,-1,"Remains of 3 humans recovered from shark, but ...",Y,NaN,Allegedly a 33-foot shark,"Taranaki Herald, 6/2/1908",1908.06.02.R-Matupi.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,6

In [53]:
df_cleaning=df_cleaning[df_cleaning["Sex"]!="."]

In [56]:
df_cleaning["Sex"][df_cleaning["Sex"]=="M "]="M"

In [57]:
df_cleaning["Sex"][df_cleaning["Sex"]=="M "]

Series([], Name: Sex, dtype: object)

In [58]:
df_cleaning["Sex"].value_counts()

M    3911
F     495
Name: Sex, dtype: int64

In [59]:
df_cleaning["Activity"].value_counts()

Surfing                                                                                                         865
Swimming                                                                                                        635
Fishing                                                                                                         355
Spearfishing                                                                                                    297
Wading                                                                                                          131
Diving                                                                                                           90
Standing                                                                                                         89
Snorkeling                                                                                                       74
Bathing                                                                                                          66
Scuba diving                                                                                                     61
Body boarding                                                                                                    54
Body surfing                                                                                                     45
Swimming                                                                                                         39
Treading water                                                                                                   30
Kayaking                                                                                                         26
Boogie boarding                                                                                                  24
Pearl diving                                                                                                     22
Free diving                                                                                                      21
Windsurfing                                                                                                      18
Boogie Boarding                                                                                                  15
Shark fishing                                                                                                    14
Walking                                                                                                          13
Surf skiing                                                                                                      12
Fishing                                                                                                          11
Rowing                                                                                                           11
Surf-skiing                                                                                                      11
Fishing for sharks                                                                                               10
Floating                                                                                                         10
Kayak Fishing                                                                                                    10
Canoeing                                                                                                          9
                                                                                                               ...
Swimming in the channel                                                                                           1
Taking boat from California to Florida when it ran aground & he was swimming back to boat                         1
Bathing with her mother                                                                                           1
On expedition filming a feature movie & standing on tripod                                                        1
Skin diving                                                                                                       1
Kitesurfing                                                                                                       1
Attempting to rescue drowning man                                                                                 1
Fell overboard?                                                                                                   1
The 6711-ton American freighter & troop transport Cape San Juan was torpedoed by the Japanese submarine I-21      1
Testing anti-shark cage                                                                                           1
Rowing toward snapper grounds                                                                                     1
Diving for pearls                                                                                                 1
Playing on rock, slipped & fell into the water                                                                    1
Crouching in the water                                                                                            1
Spearfishing, carrying his catch                                                                                  1
Playing in knee-deep water                                                                                        1
Hunting turtle                                                                                                    1
Fishing for yellowtail, Seriola quinqueradiata                                                                    1
"Swimming vigorously"                                                                                             1
Sitting in bow of her father's 5 m boat                                                                           1
Windsurfing, but sitting on his board                                                                             1
Diving off jetty                                                                                                  1
Lobstering                                                                                                        1
Swimming out to porpoises                                                                                         1
Washing clothes on stairs                                                                                         1
Stuffing a shark into an automobile                                                                               1
Body surfing?                                                                                                     1
Free diving / modeling                                                                                            1
Swimming or wading out  to warn bathers that a shark had been seen                                                1
Fell from wharf into water & attacked immediately                                                                 1
Name: Activity, Length: 1203, dtype: int64

In [98]:

def cleanactivity(act):
    if "Surf" in act or "Body" in act or "Boogie" in act or "surf" in act or "Paddleskiing" in act\
    or "Riding" in act or "Paddle" in act:
        return "Surfing"
    elif "Swimming" in act or "swimming" in act or "Floating" in act or "Tread" in act or "Bath" in act\
    or "bath" in act or "Splash" in act or "Jump" in act or "Playing" in act:
        return "Swimming"
    elif (("Fishing" in act or "fishing" in act) and ("shark" in act or "Shark" in act)) or ("shark" in act and "net" in act):
        return "Fishing sharks"
    elif "Fishing" in act or "fishing" in act or "Shrimping" in act:
        return "Fishing"
    elif "Walk" in act or "walk" in act or "Stand" in act or "Wading" in act:
        return "Walking"
    elif "Diving" in act or "Dive" in act or "diving" in act or "dive" in act:
        return "Diving"
    elif "Canoeing" in act or "Kayak" in act or "Boating" in act or "boat" in act or "Rowing" in act \
    or "rowing" in act or "overboard" in act or "Sea Disaster" in act or "Shipwreck" in act or "ship" in act:
        return "Boat"
    elif "Spearfishing" in act or "Spearing" in act:
        return "Spearfishing"
    else:
        return act
    
wdf = df_cleaning.copy()
wdf['Activity'].fillna("Unknown",inplace=True)
wdf["Activity"].apply(str)
wdf["Activity"].apply(cleanactivity).value_counts()

Surfing                                                                                                                                         1238
Fishing                                                                                                                                          788
Swimming                                                                                                                                         751
Diving                                                                                                                                           303
Unknown                                                                                                                                          271
Walking                                                                                                                                          233
Boat                                                                                                                                             133
Snorkeling                                                                                                                                        74
Fishing sharks                                                                                                                                    60
Sea disaster                                                                                                                                       6
Lifesaving drill                                                                                                                                   4
Spearfishing                                                                                                                                       4
Tagging sharks                                                                                                                                     3
Shark watching                                                                                                                                     3
Their 9 m launch was run down by a 25,000-ton Japanese freighter  on the night of 3-11-1977 & they drifted, clinging to an icebox for 2 days       3
Escaping from Alacatraz                                                                                                                            3
Feeding fish                                                                                                                                       3
The Christie V sank on 11/6/1988, survivors were adrift on a dinghy                                                                                2
Sitting in the water                                                                                                                               2
Kiteboarding                                                                                                                                       2
"Flying Tiger" transport plane went down with 5 men onboard                                                                                        2
                                                                                                                                                   2
Murder                                                                                                                                             2
Sailing                                                                                                                                            2
Teasing a shark                                                                                                                                    2
Finning the shark that bit him                                                                                                                     2
Sitting in shallows                                                                                                                                2
Kite boarding                                                                                                                                      2
Jet skiing                                                                                                                                         2
Attempting to kill a shark with explosives                                                                                                         2
                                                                                                                                                ...
Collecting dynamited fish                                                                                                                          1
Captured Allied soldiers were squeezed into 3' bamboo pig baskets & fed to waiting sharks                                                          1
Crouching in 2' of water                                                                                                                           1
Steinhart Aquarium                                                                                                                                 1
Killing  sharks                                                                                                                                    1
Washing his feet                                                                                                                                   1
Collecting fish from net                                                                                                                           1
Hauling dead shark aboard, when another shark leapt out of the water & bit him                                                                     1
Pacific Seafarer of US Navy                                                                                                                        1
Helping men land a shark                                                                                                                           1
Watching seals                                                                                                                                     1
A 210-ton brig was sunk by a Japanese submarine. Some of the survivors were machine-gunned & some were taken by sharks                             1
Measuring sharks                                                                                                                                   1
SS Ethel Skakel foundered in Central America Hurricane of 1941                                                                                     1
Hunting lobsters in 2.4 m of water                                                                                                                 1
Filming 5' blue shark                                                                                                                              1
16' catamaran capsized previous night, occupants stayed with wreckage until morning, then attempted to swim ashore                                 1
Resting on body board                                                                                                                              1
Crossing the bay at the ford                                                                                                                       1
Removing hook from shark                                                                                                                           1
Setting crayfish pots                                                                                                                              1
Thrashing the water / imitating the shark victim from "Jaws"                                                                                       1
Overturned skiff                                                                                                                                   1
In waist-deep water                                                                                                                                1
Removing shark from tank in nightclub                                                                                                              1
Filming underwater, carrying powerhead                                                                                                             1
Adrift after wave swamped engine                                                                                                                   1
Went to aid of child being menaced by the shark                                                                                                    1
Hospital Ship Centaur torpedoed & sunk by the Japanese submarine I-177                                                                             1
Paddling in knee-deep water                                                                                                                        1
Name: Activity, Length: 288, dtype: int64

In [96]:
print(df_cleaning.shape)
df_cleaning = df_cleaning[df_cleaning["Year"]>1940]
print(df_cleaning.shape)

(4878, 23)
(4175, 23)